use super::*;

pub(super) fn validate_reports_release_check(
    paths: &[Utf8PathBuf],
    required: bool,
) -> ReleaseCheckItem {
    if paths.is_empty() {
        return optional_release_check_missing(
            "vst3 validate reports",
            required,
            "pass one or more `--validate-report <path>` files generated by `vesty validate --strict --report <path>`",
        );
    }

    let mut failures = Vec::new();
    let mut bundles = Vec::new();
    let mut platforms = Vec::new();
    for path in paths {
        match read_validate_report(path) {
            Ok(report) => {
                if let Err(error) = validate_release_validate_report(&report) {
                    failures.push(format!("{path}: {error}"));
                } else {
                    collect_validate_report_platforms(&report, &mut platforms);
                    bundles.push(report.bundle);
                }
            }
            Err(error) => failures.push(format!("{path}: {error}")),
        }
    }

    if failures.is_empty() {
        ReleaseCheckItem {
            name: "vst3 validate reports".to_string(),
            status: "ok".to_string(),
            value: format!(
                "{} validate report(s): {}; platforms: {}",
                paths.len(),
                bundles.join(", "),
                format_platform_coverage(&mut platforms)
            ),
            hint: None,
        }
    } else {
        ReleaseCheckItem {
            name: "vst3 validate reports".to_string(),
            status: "failed".to_string(),
            value: failures.join("; "),
            hint: Some(
                "run `vesty validate <bundle.vst3> --strict --report <path>` with Steinberg validator configured"
                    .to_string(),
            ),
        }
    }
}

pub(super) fn static_validate_reports_release_check(
    paths: &[Utf8PathBuf],
    required: bool,
) -> ReleaseCheckItem {
    if paths.is_empty() {
        return optional_release_check_missing(
            "vst3 static validate reports",
            required,
            "pass one or more `--static-validate-report <path>` files generated by `vesty validate --static-only --strict --report <path>`",
        );
    }

    let mut failures = Vec::new();
    let mut bundles = Vec::new();
    let mut platforms = Vec::new();
    for path in paths {
        match read_validate_report(path) {
            Ok(report) => {
                if let Err(error) = validate_static_validate_report(&report) {
                    failures.push(format!("{path}: {error}"));
                } else {
                    collect_validate_report_platforms(&report, &mut platforms);
                    bundles.push(report.bundle);
                }
            }
            Err(error) => failures.push(format!("{path}: {error}")),
        }
    }

    if failures.is_empty() {
        ReleaseCheckItem {
            name: "vst3 static validate reports".to_string(),
            status: "ok".to_string(),
            value: format!(
                "{} static validate report(s): {}; platforms: {}",
                paths.len(),
                bundles.join(", "),
                format_platform_coverage(&mut platforms)
            ),
            hint: None,
        }
    } else {
        ReleaseCheckItem {
            name: "vst3 static validate reports".to_string(),
            status: "failed".to_string(),
            value: failures.join("; "),
            hint: Some(
                "run `vesty validate <bundle.vst3> --static-only --strict --report <path>` after packaging in CI"
                    .to_string(),
            ),
        }
    }
}

pub(super) const REQUIRED_EXAMPLE_BUNDLES: [&str; 3] = [
    "VestyGain.vst3",
    "VestyWebUIDemo.vst3",
    "VestyMIDISynth.vst3",
];
pub(super) const REQUIRED_EXAMPLE_VALIDATE_PLATFORMS: [&str; 3] =
    ["linux-x64", "macos", "windows-x64"];
pub(super) const ASSET_MANIFEST_FILE: &str = "assets.manifest.json";
pub(super) const REQUIRED_WEB_UI_EXAMPLE_BUNDLE: &str = "VestyWebUIDemo.vst3";

pub(super) fn example_validate_coverage_release_check(
    paths: &[Utf8PathBuf],
    require_all_platforms: bool,
) -> ReleaseCheckItem {
    if paths.is_empty() {
        return optional_release_check_missing(
            "vst3 example validator coverage",
            require_all_platforms,
            "release evidence should include Steinberg validator-passed reports for VestyGain, VestyWebUIDemo and VestyMIDISynth on macOS, Windows x64 and Linux x64; generate them with `vesty validate --strict --report <path>`",
        );
    }

    let mut failures = Vec::new();
    let mut bundle_coverage = BTreeSet::new();
    let mut platform_coverage = BTreeSet::new();
    let mut coverage = BTreeSet::<String>::new();
    for path in paths {
        match read_validate_report(path) {
            Ok(report) => {
                if let Err(error) = validate_release_validate_report(&report) {
                    failures.push(format!("{path}: {error}"));
                    continue;
                }
                let bundle = validate_report_bundle_name(&report);
                if REQUIRED_EXAMPLE_BUNDLES.contains(&bundle.as_str()) {
                    if let Err(error) = validate_required_example_report_bundle(
                        path,
                        &bundle,
                        &REQUIRED_EXAMPLE_BUNDLES,
                    ) {
                        failures.push(format!("{path}: {error}"));
                        continue;
                    }
                    if let Err(error) =
                        validate_required_example_parameter_manifest_evidence(&report, &bundle)
                    {
                        failures.push(format!("{path}: {error}"));
                        continue;
                    }
                    if let Err(error) = validate_required_example_asset_evidence(&report, &bundle) {
                        failures.push(format!("{path}: {error}"));
                        continue;
                    }
                    let platform = match validate_required_example_report_platform(
                        path,
                        &report,
                        &REQUIRED_EXAMPLE_VALIDATE_PLATFORMS,
                        "validator-passed example report",
                    ) {
                        Ok(platform) => platform,
                        Err(error) => {
                            failures.push(format!("{path}: {error}"));
                            continue;
                        }
                    };
                    if require_all_platforms
                        && let Err(error) =
                            validate_required_binary_export_evidence(&report, &bundle, platform)
                    {
                        failures.push(format!("{path}: {error}"));
                        continue;
                    }
                    let key = format!("{bundle}@{platform}");
                    if coverage.contains(&key) {
                        failures.push(format!(
                            "{path}: duplicate validator-passed example report for {key}"
                        ));
                        continue;
                    }
                    bundle_coverage.insert(bundle.clone());
                    platform_coverage.insert(platform);
                    coverage.insert(key);
                }
            }
            Err(error) => failures.push(format!("{path}: {error}")),
        }
    }

    if !failures.is_empty() {
        return ReleaseCheckItem {
            name: "vst3 example validator coverage".to_string(),
            status: "failed".to_string(),
            value: failures.join("; "),
            hint: Some(
                "expected validator-passed `vesty validate --strict --report` JSON".to_string(),
            ),
        };
    }

    if coverage.is_empty() {
        return optional_release_check_missing(
            "vst3 example validator coverage",
            require_all_platforms,
            "no Vesty example validator-passed reports found; expected VestyGain, VestyWebUIDemo and VestyMIDISynth on macOS, Windows x64 and Linux x64; generate them with `vesty validate --strict --report <path>`",
        );
    }

    if require_all_platforms {
        let mut missing = Vec::new();
        for platform in REQUIRED_EXAMPLE_VALIDATE_PLATFORMS {
            for bundle in REQUIRED_EXAMPLE_BUNDLES {
                let key = format!("{bundle}@{platform}");
                if !coverage.contains(&key) {
                    missing.push(key);
                }
            }
        }
        if missing.is_empty() {
            let platforms = platform_coverage
                .iter()
                .copied()
                .collect::<Vec<_>>()
                .join(", ");
            ReleaseCheckItem {
                name: "vst3 example validator coverage".to_string(),
                status: "ok".to_string(),
                value: format!(
                    "{} example/platform validator report(s) (full release coverage; platforms: {platforms})",
                    coverage.len()
                ),
                hint: None,
            }
        } else {
            ReleaseCheckItem {
                name: "vst3 example validator coverage".to_string(),
                status: "failed".to_string(),
                value: format!("missing validator-passed reports: {}", missing.join(", ")),
                hint: Some(
                    "run `vesty validate --strict --report <path>` for all three shipped Vesty examples on macOS, Windows x64 and Linux x64 before release"
                        .to_string(),
                ),
            }
        }
    } else {
        let missing = REQUIRED_EXAMPLE_BUNDLES
            .iter()
            .filter(|bundle| !bundle_coverage.contains(**bundle))
            .copied()
            .collect::<Vec<_>>();
        let mut present = bundle_coverage
            .iter()
            .map(String::as_str)
            .collect::<Vec<_>>();
        present.sort_unstable();
        let platforms = platform_coverage
            .iter()
            .copied()
            .collect::<Vec<_>>()
            .join(", ");
        ReleaseCheckItem {
            name: "vst3 example validator coverage".to_string(),
            status: "ok".to_string(),
            value: format!(
                "{} of 3 example validator report(s): {}; platforms: {}",
                bundle_coverage.len(),
                present.join(", "),
                if platforms.is_empty() {
                    "unknown"
                } else {
                    platforms.as_str()
                }
            ),
            hint: (!missing.is_empty()).then(|| {
                format!(
                    "full release coverage still needs validator reports for {}",
                    missing.join(", ")
                )
            }),
        }
    }
}

pub(super) const REQUIRED_EXAMPLE_STATIC_VALIDATE_PLATFORMS: [&str; 3] =
    REQUIRED_EXAMPLE_VALIDATE_PLATFORMS;

pub(super) fn example_static_validate_coverage_release_check(
    paths: &[Utf8PathBuf],
    require_all_platforms: bool,
) -> ReleaseCheckItem {
    if paths.is_empty() {
        return optional_release_check_missing(
            "ci example static validate coverage",
            require_all_platforms,
            "CI package smoke should upload `vesty validate --static-only --strict --report <path>` reports for gain, web-ui-param-demo and midi-synth",
        );
    }

    let mut failures = Vec::new();
    let mut coverage = BTreeSet::new();
    let mut present_platforms = BTreeSet::new();
    for path in paths {
        match read_validate_report(path) {
            Ok(report) => {
                if let Err(error) = validate_static_validate_report(&report) {
                    failures.push(format!("{path}: {error}"));
                    continue;
                }
                let bundle = validate_report_bundle_name(&report);
                if !REQUIRED_EXAMPLE_BUNDLES.contains(&bundle.as_str()) {
                    continue;
                }
                if let Err(error) = validate_required_example_report_bundle(
                    path,
                    &bundle,
                    &REQUIRED_EXAMPLE_BUNDLES,
                ) {
                    failures.push(format!("{path}: {error}"));
                    continue;
                }
                if let Err(error) =
                    validate_required_example_parameter_manifest_evidence(&report, &bundle)
                {
                    failures.push(format!("{path}: {error}"));
                    continue;
                }
                if let Err(error) = validate_required_example_asset_evidence(&report, &bundle) {
                    failures.push(format!("{path}: {error}"));
                    continue;
                }
                let platform = match validate_required_example_report_platform(
                    path,
                    &report,
                    &REQUIRED_EXAMPLE_STATIC_VALIDATE_PLATFORMS,
                    "static example report",
                ) {
                    Ok(platform) => platform,
                    Err(error) => {
                        failures.push(format!("{path}: {error}"));
                        continue;
                    }
                };
                if require_all_platforms
                    && let Err(error) =
                        validate_required_binary_export_evidence(&report, &bundle, platform)
                {
                    failures.push(format!("{path}: {error}"));
                    continue;
                }
                let key = format!("{bundle}@{platform}");
                if coverage.contains(&key) {
                    failures.push(format!("{path}: duplicate static example report for {key}"));
                    continue;
                }
                present_platforms.insert(platform);
                coverage.insert(key);
            }
            Err(error) => failures.push(format!("{path}: {error}")),
        }
    }

    if !failures.is_empty() {
        return ReleaseCheckItem {
            name: "ci example static validate coverage".to_string(),
            status: "failed".to_string(),
            value: failures.join("; "),
            hint: Some(
                "expected parseable `vesty validate --static-only --strict --report` JSON"
                    .to_string(),
            ),
        };
    }

    if coverage.is_empty() {
        return optional_release_check_missing(
            "ci example static validate coverage",
            require_all_platforms,
            "no Vesty example static validate reports found; expected VestyGain, VestyWebUIDemo and VestyMIDISynth CI artifacts",
        );
    }

    let platforms_to_check = if require_all_platforms {
        REQUIRED_EXAMPLE_STATIC_VALIDATE_PLATFORMS.to_vec()
    } else {
        present_platforms.iter().copied().collect::<Vec<_>>()
    };
    let mut missing = Vec::new();
    for platform in &platforms_to_check {
        for bundle in REQUIRED_EXAMPLE_BUNDLES {
            let key = format!("{bundle}@{platform}");
            if !coverage.contains(&key) {
                missing.push(key);
            }
        }
    }

    if missing.is_empty() {
        let platforms = present_platforms
            .iter()
            .copied()
            .collect::<Vec<_>>()
            .join(", ");
        let full = if require_all_platforms {
            "full release coverage"
        } else {
            "per-platform CI smoke coverage"
        };
        ReleaseCheckItem {
            name: "ci example static validate coverage".to_string(),
            status: "ok".to_string(),
            value: format!(
                "{} example/platform entries ({full}; platforms: {platforms})",
                coverage.len()
            ),
            hint: None,
        }
    } else {
        ReleaseCheckItem {
            name: "ci example static validate coverage".to_string(),
            status: "failed".to_string(),
            value: format!("missing: {}", missing.join(", ")),
            hint: Some(
                "package and run `vesty validate --static-only --strict --report <path>` for all three examples on linux-x64, macos and windows-x64"
                    .to_string(),
            ),
        }
    }
}

pub(super) fn validate_required_example_report_bundle(
    path: &Utf8Path,
    bundle: &str,
    required_bundles: &[&'static str],
) -> Result<(), Box<dyn std::error::Error>> {
    if let Some(path_bundle) = validate_report_file_name_bundle(path, required_bundles)?
        && path_bundle != bundle
    {
        return Err(format!(
            "example report file name indicates {path_bundle}, but report bundle is {bundle}"
        )
        .into());
    }
    Ok(())
}

pub(super) fn validate_report_file_name_bundle(
    path: &Utf8Path,
    required_bundles: &[&'static str],
) -> Result<Option<&'static str>, Box<dyn std::error::Error>> {
    let tokens = file_name_tokens(path);
    let mut found = required_bundles
        .iter()
        .copied()
        .filter(|bundle| file_name_tokens_contain_bundle(&tokens, bundle))
        .collect::<Vec<_>>();
    found.sort_unstable();
    found.dedup();
    match found.as_slice() {
        [] => Ok(None),
        [bundle] => Ok(Some(*bundle)),
        _ => Err(format!(
            "validate report file name contains multiple example bundle labels: {}",
            found.join(", ")
        )
        .into()),
    }
}

pub(super) fn validate_required_example_report_platform(
    path: &Utf8Path,
    report: &ValidateReport,
    required_platforms: &[&'static str],
    report_label: &str,
) -> Result<&'static str, Box<dyn std::error::Error>> {
    let platforms = validate_report_platforms(report);
    if platforms.is_empty() {
        return Err(format!(
            "{report_label} must contain exactly one release platform; could not infer platform from static binaries"
        )
        .into());
    }
    if platforms.len() != 1 {
        return Err(format!(
            "{report_label} must contain exactly one release platform; found {}",
            format_platform_set(&platforms)
        )
        .into());
    }

    let Some(platform) = platforms.iter().next().copied() else {
        return Err(format!("{report_label} platform set unexpectedly became empty").into());
    };
    if !required_platforms.contains(&platform) {
        return Err(format!("{report_label} uses unsupported platform `{platform}`").into());
    }

    if let Some(path_platform) = validate_report_file_name_platform(path, required_platforms)?
        && path_platform != platform
    {
        return Err(format!(
            "{report_label} file name indicates {path_platform}, but static binaries indicate {platform}"
        )
        .into());
    }

    Ok(platform)
}

pub(super) fn validate_report_file_name_platform(
    path: &Utf8Path,
    required_platforms: &[&'static str],
) -> Result<Option<&'static str>, Box<dyn std::error::Error>> {
    let tokens = file_name_tokens(path);
    let mut found = required_platforms
        .iter()
        .copied()
        .filter(|platform| file_name_tokens_contain_platform(&tokens, platform))
        .collect::<Vec<_>>();
    found.sort_unstable();
    found.dedup();
    match found.as_slice() {
        [] => Ok(None),
        [platform] => Ok(Some(*platform)),
        _ => Err(format!(
            "validate report file name contains multiple platform labels: {}",
            found.join(", ")
        )
        .into()),
    }
}

pub(super) fn file_name_tokens(path: &Utf8Path) -> Vec<String> {
    let Some(file_name) = path.file_name() else {
        return Vec::new();
    };
    file_name
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() {
                ch.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect::<String>()
        .split('-')
        .filter(|part| !part.is_empty())
        .map(ToString::to_string)
        .collect()
}

pub(super) fn file_name_tokens_contain_bundle(tokens: &[String], bundle: &str) -> bool {
    let bundle_name = bundle.strip_suffix(".vst3").unwrap_or(bundle);
    let compact_bundle_token = file_name_label_compact_token(bundle_name);
    if !compact_bundle_token.is_empty()
        && tokens
            .iter()
            .any(|token| token.as_str() == compact_bundle_token)
    {
        return true;
    }
    let bundle_tokens = file_name_label_tokens(bundle_name);
    file_name_tokens_contain_sequence(tokens, &bundle_tokens)
}

pub(super) fn file_name_tokens_contain_platform(tokens: &[String], platform: &str) -> bool {
    let platform_tokens = file_name_label_tokens(platform);
    file_name_tokens_contain_sequence(tokens, &platform_tokens)
}

pub(super) fn file_name_label_tokens(label: &str) -> Vec<String> {
    let chars = label.chars().collect::<Vec<_>>();
    let mut tokens = Vec::new();
    let mut current = String::new();
    for (index, ch) in chars.iter().copied().enumerate() {
        if !ch.is_ascii_alphanumeric() {
            if !current.is_empty() {
                tokens.push(std::mem::take(&mut current));
            }
            continue;
        }

        let previous = index
            .checked_sub(1)
            .and_then(|previous| chars.get(previous));
        let next = chars.get(index + 1).copied();
        let camel_boundary = ch.is_ascii_uppercase()
            && !current.is_empty()
            && (previous.is_some_and(|previous| {
                previous.is_ascii_lowercase() || previous.is_ascii_digit()
            }) || next.is_some_and(|next| next.is_ascii_lowercase()));
        if camel_boundary {
            tokens.push(std::mem::take(&mut current));
        }
        current.push(ch.to_ascii_lowercase());
    }
    if !current.is_empty() {
        tokens.push(current);
    }
    tokens
}

pub(super) fn file_name_label_compact_token(label: &str) -> String {
    label
        .chars()
        .filter(|ch| ch.is_ascii_alphanumeric())
        .map(|ch| ch.to_ascii_lowercase())
        .collect()
}

pub(super) fn file_name_tokens_contain_sequence(tokens: &[String], sequence: &[String]) -> bool {
    if sequence.is_empty() || tokens.len() < sequence.len() {
        return false;
    }
    tokens.windows(sequence.len()).any(|window| {
        window
            .iter()
            .map(String::as_str)
            .eq(sequence.iter().map(String::as_str))
    })
}

pub(super) fn format_platform_set(platforms: &BTreeSet<&'static str>) -> String {
    platforms.iter().copied().collect::<Vec<_>>().join(", ")
}

pub(super) fn validate_required_example_parameter_manifest_evidence(
    report: &ValidateReport,
    bundle: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    if !REQUIRED_EXAMPLE_BUNDLES.contains(&bundle) {
        return Ok(());
    }
    let has_manifest = report
        .static_check
        .parameter_manifest
        .as_deref()
        .is_some_and(|path| manifest_evidence_path_matches(path, bundle, PARAMETER_MANIFEST_FILE));
    if has_manifest {
        Ok(())
    } else {
        let actual = report
            .static_check
            .parameter_manifest
            .as_deref()
            .filter(|path| !path.trim().is_empty())
            .unwrap_or("<missing>");
        Err(format!(
            "{bundle} report is missing parameter manifest evidence at {bundle}/Contents/Resources/{PARAMETER_MANIFEST_FILE}; actual static_check.parameter_manifest: {actual}"
        )
        .into())
    }
}

pub(super) fn validate_required_binary_export_evidence(
    report: &ValidateReport,
    bundle: &str,
    platform: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let matching = report
        .static_check
        .binary_exports
        .iter()
        .filter(|check| check.platform == platform)
        .collect::<Vec<_>>();
    if matching.is_empty() {
        return Err(format!(
            "{bundle}@{platform} report is missing binary export evidence in static_check.binary_exports"
        )
        .into());
    }
    if matching
        .iter()
        .any(|check| binary_export_check_proves_platform(check, platform))
    {
        return Ok(());
    }

    let details = matching
        .iter()
        .map(|check| {
            let missing = if check.missing_symbols.is_empty() {
                "<none>".to_string()
            } else {
                check.missing_symbols.join(", ")
            };
            format!("{} status={} missing={missing}", check.binary, check.status)
        })
        .collect::<Vec<_>>()
        .join("; ");
    Err(format!(
        "{bundle}@{platform} report must include ok binary export evidence; actual: {details}"
    )
    .into())
}

pub(super) fn manifest_evidence_path_matches(path: &str, bundle: &str, file_name: &str) -> bool {
    report_path_has_bundle_tail(path, bundle, &["Contents", "Resources", file_name])
}

pub(super) fn validate_required_example_asset_evidence(
    report: &ValidateReport,
    bundle: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    if bundle != REQUIRED_WEB_UI_EXAMPLE_BUNDLE {
        return Ok(());
    }
    let has_manifest = report
        .static_check
        .asset_manifest
        .as_deref()
        .is_some_and(|path| manifest_evidence_path_matches(path, bundle, ASSET_MANIFEST_FILE));
    if has_manifest && report.static_check.asset_count > 0 {
        Ok(())
    } else {
        let actual = report
            .static_check
            .asset_manifest
            .as_deref()
            .filter(|path| !path.trim().is_empty())
            .unwrap_or("<missing>");
        Err(format!(
            "{REQUIRED_WEB_UI_EXAMPLE_BUNDLE} report is missing UI asset manifest evidence at {REQUIRED_WEB_UI_EXAMPLE_BUNDLE}/Contents/Resources/{ASSET_MANIFEST_FILE}; actual static_check.asset_manifest: {actual}; asset_count: {}",
            report.static_check.asset_count
        )
        .into())
    }
}

pub(super) fn read_validate_report(
    path: &Utf8Path,
) -> Result<ValidateReport, Box<dyn std::error::Error>> {
    let text = read_text_file_no_symlink("validate report", path)?;
    serde_json::from_str(&text)
        .map_err(|error| format!("invalid validate report JSON: {error}").into())
}

pub(super) const VALIDATE_REPORT_TEXT_MAX_BYTES: usize = 8 * 1024;
pub(super) const VALIDATE_REPORT_LOG_MAX_BYTES: usize = 256 * 1024;
pub(super) const VALIDATE_REPORT_MAX_BINARIES: usize = 64;
pub(super) const VALIDATE_REPORT_MAX_BINARY_EXPORTS: usize = 64;
pub(super) const VALIDATE_REPORT_MAX_SYMBOLS: usize = 64;

pub(super) fn validate_validate_report_shape(
    report: &ValidateReport,
) -> Result<(), Box<dyn std::error::Error>> {
    validate_validate_report_text("validate report bundle", &report.bundle)?;
    validate_static_bundle_check_shape(&report.static_check)?;
    validate_validator_check_shape(&report.validator)?;
    Ok(())
}

pub(super) fn validate_static_bundle_check_shape(
    check: &StaticBundleCheck,
) -> Result<(), Box<dyn std::error::Error>> {
    validate_validate_report_text("static bundle check status", &check.status)?;
    validate_optional_validate_report_text("static bundle check moduleinfo", &check.moduleinfo)?;
    validate_optional_validate_report_text(
        "static bundle check parameter manifest",
        &check.parameter_manifest,
    )?;
    validate_optional_validate_report_text(
        "static bundle check asset manifest",
        &check.asset_manifest,
    )?;
    validate_optional_validate_report_text("static bundle check error", &check.error)?;
    if check.binaries.len() > VALIDATE_REPORT_MAX_BINARIES {
        return Err(format!(
            "static bundle check has too many binaries: {} exceeds maximum {VALIDATE_REPORT_MAX_BINARIES}",
            check.binaries.len()
        )
        .into());
    }
    validate_validate_report_text_list(
        "static bundle check binary",
        &check.binaries,
        VALIDATE_REPORT_MAX_BINARIES,
    )?;
    let mut seen_binary_paths = BTreeSet::new();
    for binary in &check.binaries {
        let Some(key) = report_path_key(binary) else {
            continue;
        };
        if !seen_binary_paths.insert(key.clone()) {
            return Err(format!("duplicate static bundle check binary path `{key}`").into());
        }
    }
    if check.binary_exports.len() > VALIDATE_REPORT_MAX_BINARY_EXPORTS {
        return Err(format!(
            "static bundle check has too many binary export checks: {} exceeds maximum {VALIDATE_REPORT_MAX_BINARY_EXPORTS}",
            check.binary_exports.len()
        )
        .into());
    }
    let mut seen_export_checks = BTreeSet::new();
    for export_check in &check.binary_exports {
        validate_binary_export_check_shape(export_check)?;
        let binary = report_path_key(&export_check.binary)
            .unwrap_or_else(|| export_check.binary.trim().to_string());
        let key = format!("{}@{}", binary, export_check.platform.trim());
        if !seen_export_checks.insert(key.clone()) {
            return Err(format!("duplicate binary export check `{key}`").into());
        }
    }
    Ok(())
}

pub(super) fn validate_binary_export_check_shape(
    check: &BinaryExportCheck,
) -> Result<(), Box<dyn std::error::Error>> {
    validate_validate_report_text("binary export check binary", &check.binary)?;
    validate_validate_report_text("binary export check platform", &check.platform)?;
    validate_validate_report_text("binary export check status", &check.status)?;
    validate_optional_validate_report_text("binary export check tool", &check.tool)?;
    validate_optional_validate_report_text("binary export check error", &check.error)?;
    validate_validate_report_text_list(
        "binary export required symbol",
        &check.required_symbols,
        VALIDATE_REPORT_MAX_SYMBOLS,
    )?;
    validate_validate_report_text_list(
        "binary export found symbol",
        &check.found_symbols,
        VALIDATE_REPORT_MAX_SYMBOLS,
    )?;
    validate_validate_report_text_list(
        "binary export missing symbol",
        &check.missing_symbols,
        VALIDATE_REPORT_MAX_SYMBOLS,
    )?;
    Ok(())
}

pub(super) fn validate_validator_check_shape(
    check: &ValidatorCheck,
) -> Result<(), Box<dyn std::error::Error>> {
    validate_validate_report_text("validator status", &check.status)?;
    validate_optional_validate_report_text("validator path", &check.path)?;
    validate_optional_validate_report_log_text("validator stdout", &check.stdout)?;
    validate_optional_validate_report_log_text("validator stderr", &check.stderr)?;
    validate_optional_validate_report_text("validator reason", &check.reason)?;
    validate_optional_validate_report_text("validator error", &check.error)?;
    Ok(())
}

pub(super) fn validate_validate_report_text(label: &str, value: &str) -> Result<(), String> {
    validate_release_action_text(label, value)?;
    if value.len() > VALIDATE_REPORT_TEXT_MAX_BYTES {
        return Err(format!(
            "{label} must be at most {VALIDATE_REPORT_TEXT_MAX_BYTES} bytes"
        ));
    }
    Ok(())
}

pub(super) fn validate_optional_validate_report_text(
    label: &str,
    value: &Option<String>,
) -> Result<(), String> {
    if let Some(value) = value {
        validate_validate_report_text(label, value)?;
    }
    Ok(())
}

pub(super) fn validate_optional_validate_report_log_text(
    label: &str,
    value: &Option<String>,
) -> Result<(), String> {
    let Some(value) = value else {
        return Ok(());
    };
    if value.len() > VALIDATE_REPORT_LOG_MAX_BYTES {
        return Err(format!(
            "{label} must be at most {VALIDATE_REPORT_LOG_MAX_BYTES} bytes"
        ));
    }
    if value
        .chars()
        .any(|ch| ch.is_control() && !matches!(ch, '\n' | '\r' | '\t'))
    {
        return Err(format!(
            "{label} must not contain control characters other than tab/newline"
        ));
    }
    if value.chars().any(is_release_action_unsafe_format_char) {
        return Err(format!(
            "{label} must not contain unsafe Unicode format characters"
        ));
    }
    Ok(())
}

pub(super) fn validate_validate_report_text_list(
    label: &str,
    values: &[String],
    max_items: usize,
) -> Result<(), Box<dyn std::error::Error>> {
    if values.len() > max_items {
        return Err(format!(
            "{label} list has too many items: {} exceeds maximum {max_items}",
            values.len()
        )
        .into());
    }
    let mut seen = BTreeSet::new();
    for value in values {
        validate_validate_report_text(label, value)?;
        let normalized = value.trim().to_string();
        if !seen.insert(normalized.clone()) {
            return Err(format!("duplicate {label} `{normalized}`").into());
        }
    }
    Ok(())
}

pub(super) fn non_empty_field<'a>(
    value: &'a Option<String>,
    field: &str,
) -> Result<&'a str, String> {
    value
        .as_deref()
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .ok_or_else(|| format!("{field} is missing"))
}

pub(super) fn empty_or_missing(value: &Option<String>) -> bool {
    value.as_deref().map(str::trim).unwrap_or("").is_empty()
}

pub(super) fn normalize_report_path(path: &str) -> Option<String> {
    let normalized = path.trim().replace('\\', "/");
    if normalized.is_empty() {
        None
    } else {
        Some(normalized)
    }
}

pub(super) fn portable_report_path(path: &Utf8Path) -> String {
    path.as_str().replace('\\', "/")
}

pub(super) fn release_report_paths_equal(left: &str, right: &str) -> bool {
    match (
        lexical_release_report_path(left),
        lexical_release_report_path(right),
    ) {
        (Ok(left), Ok(right)) => left == right,
        _ => false,
    }
}

#[cfg(test)]
pub(super) fn release_report_path_ends_with(path: &str, suffix: &str) -> bool {
    let (Ok(path), Ok(suffix)) = (
        lexical_release_report_path(path),
        lexical_release_report_path(suffix),
    ) else {
        return false;
    };
    path.components.ends_with(&suffix.components)
}

pub(super) fn report_path_components(path: &str) -> Option<Vec<String>> {
    let normalized = normalize_report_path(path)?;
    let components = normalized
        .split('/')
        .filter(|component| !component.is_empty() && *component != ".")
        .map(ToString::to_string)
        .collect::<Vec<_>>();
    if components.is_empty() || components.iter().any(|component| component == "..") {
        None
    } else {
        Some(components)
    }
}

pub(super) fn report_path_key(path: &str) -> Option<String> {
    report_path_components(path).map(|components| components.join("/"))
}

pub(super) fn report_bundle_component_index(components: &[String]) -> Option<usize> {
    components
        .iter()
        .position(|component| component.to_ascii_lowercase().ends_with(".vst3"))
}

pub(super) fn report_path_has_bundle_tail(path: &str, bundle: &str, tail: &[&str]) -> bool {
    let Some(components) = report_path_components(path) else {
        return false;
    };
    let Some(index) = report_bundle_component_index(&components) else {
        return false;
    };
    components[index] == bundle
        && components[index + 1..]
            .iter()
            .map(String::as_str)
            .eq(tail.iter().copied())
}

pub(super) fn report_binary_path_matches_bundle(path: &str, bundle: &str) -> bool {
    let Some(components) = report_path_components(path) else {
        return false;
    };
    let Some(index) = report_bundle_component_index(&components) else {
        return false;
    };
    components[index] == bundle
        && components
            .get(index + 1)
            .is_some_and(|component| component == "Contents")
        && components.get(index + 2).is_some_and(|component| {
            matches!(component.as_str(), "MacOS" | "x86_64-win" | "x86_64-linux")
        })
        && components.len() > index + 3
}

pub(super) fn validate_report_paths_self_consistent(
    report: &ValidateReport,
) -> Result<(), Box<dyn std::error::Error>> {
    let bundle = validate_report_bundle_name(report);
    if bundle.trim().is_empty() {
        return Err("validate report bundle is missing".into());
    }
    if bundle.chars().any(char::is_control) {
        return Err("validate report bundle contains control characters".into());
    }
    if !bundle.to_ascii_lowercase().ends_with(".vst3") {
        return Err(format!("validate report bundle must end with .vst3: {bundle}").into());
    }

    if report.static_check.status != "ok" {
        return Ok(());
    }

    let moduleinfo = non_empty_field(
        &report.static_check.moduleinfo,
        "static bundle check moduleinfo",
    )
    .map_err(|error| -> Box<dyn std::error::Error> { error.into() })?;
    if !report_path_has_bundle_tail(
        moduleinfo,
        &bundle,
        &["Contents", "Resources", "moduleinfo.json"],
    ) {
        return Err(format!(
            "static bundle check moduleinfo path does not belong to {bundle}: {moduleinfo}"
        )
        .into());
    }

    let mut binary_paths = BTreeSet::new();
    for binary in &report.static_check.binaries {
        let Some(normalized) = report_path_key(binary) else {
            return Err("static bundle check contains an empty binary path".into());
        };
        if !report_binary_path_matches_bundle(&normalized, &bundle) {
            return Err(format!(
                "static bundle check binary path does not belong to {bundle}: {binary}"
            )
            .into());
        }
        binary_paths.insert(normalized);
    }

    for export_check in &report.static_check.binary_exports {
        let Some(normalized) = report_path_key(&export_check.binary) else {
            return Err("binary export check contains an empty binary path".into());
        };
        if !report_binary_path_matches_bundle(&normalized, &bundle) {
            return Err(format!(
                "binary export check path does not belong to {bundle}: {}",
                export_check.binary
            )
            .into());
        }
        if !binary_paths.contains(&normalized) {
            return Err(format!(
                "binary export check references a binary not listed in static_check.binaries: {}",
                export_check.binary
            )
            .into());
        }
    }

    if let Some(path) = report
        .static_check
        .parameter_manifest
        .as_deref()
        .map(str::trim)
        .filter(|path| !path.is_empty())
        && !manifest_evidence_path_matches(path, &bundle, PARAMETER_MANIFEST_FILE)
    {
        return Err(
            format!("static_check.parameter_manifest does not belong to {bundle}: {path}").into(),
        );
    }

    if let Some(path) = report
        .static_check
        .asset_manifest
        .as_deref()
        .map(str::trim)
        .filter(|path| !path.is_empty())
    {
        if !manifest_evidence_path_matches(path, &bundle, ASSET_MANIFEST_FILE) {
            return Err(
                format!("static_check.asset_manifest does not belong to {bundle}: {path}").into(),
            );
        }
        if report.static_check.asset_count == 0 {
            return Err("static_check.asset_manifest is present but asset_count is 0".into());
        }
    } else if report.static_check.asset_count != 0 {
        return Err(format!(
            "static_check.asset_count is {} but asset_manifest is missing",
            report.static_check.asset_count
        )
        .into());
    }

    Ok(())
}

pub(super) fn validate_static_bundle_check_self_consistent(
    check: &StaticBundleCheck,
) -> Result<(), Box<dyn std::error::Error>> {
    match check.status.as_str() {
        "ok" => {
            non_empty_field(&check.moduleinfo, "static bundle check moduleinfo")
                .map_err(|error| -> Box<dyn std::error::Error> { error.into() })?;
            if check.binaries.is_empty() {
                return Err("static bundle check has no platform binaries".into());
            }
            if let Some(error) = check.error.as_deref().map(str::trim)
                && !error.is_empty()
            {
                return Err(
                    format!("static bundle check is ok but still lists error: {error}").into(),
                );
            }
            validate_static_bundle_binary_export_checks(check)?;
        }
        "failed" => {
            non_empty_field(&check.error, "static bundle check failure error")
                .map_err(|error| -> Box<dyn std::error::Error> { error.into() })?;
            if check
                .moduleinfo
                .as_deref()
                .map(str::trim)
                .is_some_and(|value| !value.is_empty())
            {
                return Err("static bundle check failed but still lists moduleinfo".into());
            }
            if !check.binaries.is_empty() {
                return Err("static bundle check failed but still lists binaries".into());
            }
            if !check.binary_exports.is_empty() {
                return Err("static bundle check failed but still lists binary exports".into());
            }
            if check
                .parameter_manifest
                .as_deref()
                .map(str::trim)
                .is_some_and(|value| !value.is_empty())
            {
                return Err("static bundle check failed but still lists parameter manifest".into());
            }
            if check
                .asset_manifest
                .as_deref()
                .map(str::trim)
                .is_some_and(|value| !value.is_empty())
            {
                return Err("static bundle check failed but still lists asset manifest".into());
            }
            if check.asset_count != 0 {
                return Err(format!(
                    "static bundle check failed but still lists asset_count {}",
                    check.asset_count
                )
                .into());
            }
        }
        other => {
            return Err(format!("static bundle check has unknown status `{other}`").into());
        }
    }
    Ok(())
}

pub(super) fn validate_validator_check_self_consistent(
    check: &ValidatorCheck,
) -> Result<(), Box<dyn std::error::Error>> {
    match check.status.as_str() {
        "passed" => {
            non_empty_field(&check.path, "validator path")
                .map_err(|error| -> Box<dyn std::error::Error> { error.into() })?;
            if check.exit_code != Some(0) {
                return Err(format!(
                    "validator exit code is {}",
                    check
                        .exit_code
                        .map(|code| code.to_string())
                        .unwrap_or_else(|| "missing".to_string())
                )
                .into());
            }
            match check.tests_passed {
                Some(passed) if passed > 0 => {}
                Some(_) => return Err("validator reported 0 passed tests".into()),
                None => return Err("validator passed test count is missing".into()),
            }
            match check.tests_failed {
                Some(0) => {}
                Some(failed) => {
                    return Err(format!("validator reported {failed} failed test(s)").into());
                }
                None => return Err("validator failed test count is missing".into()),
            }
            if let Some(error) = check.error.as_deref().map(str::trim)
                && !error.is_empty()
            {
                return Err(format!("validator passed report includes error: {error}").into());
            }
            if let Some(reason) = check.reason.as_deref().map(str::trim)
                && !reason.is_empty()
            {
                return Err(format!("validator passed report includes reason: {reason}").into());
            }
            validate_validator_passed_log_runtime_state(check)?;
            validate_validator_passed_log_summary(check)?;
        }
        "failed" => {
            non_empty_field(&check.path, "validator failed report path")
                .map_err(|error| -> Box<dyn std::error::Error> { error.into() })?;
            if let Some(reason) = check.reason.as_deref().map(str::trim)
                && !reason.is_empty()
            {
                return Err(format!("validator failed report includes reason: {reason}").into());
            }
            let has_error = check
                .error
                .as_deref()
                .map(str::trim)
                .is_some_and(|error| !error.is_empty());
            let has_nonzero_exit = check.exit_code.is_some_and(|code| code != 0);
            let has_failed_tests = check.tests_failed.is_some_and(|failed| failed > 0);
            if check.tests_passed.is_some() != check.tests_failed.is_some() {
                return Err("validator failed report has partial test counts".into());
            }
            let has_runtime_failure = validator_failed_report_has_runtime_failure(check);
            if check.exit_code == Some(0) && !has_failed_tests && !has_runtime_failure {
                return Err(
                    "validator failed report has exit code 0, no failed tests and no runtime failure evidence"
                        .into(),
                );
            }
            if check.tests_failed == Some(0) && !has_nonzero_exit && !has_runtime_failure {
                return Err(
                    "validator failed report lists zero failed tests without nonzero exit or runtime failure evidence"
                        .into(),
                );
            }
            if !has_error && !has_nonzero_exit && !has_failed_tests {
                return Err(
                    "validator failed report has no error, nonzero exit code or failed test count"
                        .into(),
                );
            }
        }
        "skipped" | "not_run" | "not_found" => {
            non_empty_field(&check.reason, "validator skip reason")
                .map_err(|error| -> Box<dyn std::error::Error> { error.into() })?;
            if !empty_or_missing(&check.path) {
                return Err(format!("validator {} report includes path", check.status).into());
            }
            if check.exit_code.is_some() {
                return Err(format!("validator {} report includes exit code", check.status).into());
            }
            if check.tests_passed.is_some() {
                return Err(format!(
                    "validator {} report includes passed test count",
                    check.status
                )
                .into());
            }
            if check.tests_failed.is_some() {
                return Err(format!(
                    "validator {} report includes failed test count",
                    check.status
                )
                .into());
            }
            if !empty_or_missing(&check.stdout) {
                return Err(format!("validator {} report includes stdout", check.status).into());
            }
            if !empty_or_missing(&check.stderr) {
                return Err(format!("validator {} report includes stderr", check.status).into());
            }
            if !empty_or_missing(&check.error) {
                return Err(format!("validator {} report includes error", check.status).into());
            }
        }
        other => return Err(format!("validator has unknown status `{other}`").into()),
    }
    Ok(())
}

pub(super) fn validator_failed_report_has_runtime_failure(check: &ValidatorCheck) -> bool {
    [
        check.stdout.as_deref(),
        check.stderr.as_deref(),
        check.error.as_deref(),
    ]
    .into_iter()
    .flatten()
    .any(|text| vst3_validator_has_runtime_failure(&text.to_ascii_lowercase()))
}

pub(super) fn validate_validator_passed_log_runtime_state(
    check: &ValidatorCheck,
) -> Result<(), Box<dyn std::error::Error>> {
    for (label, text) in [
        ("stdout", check.stdout.as_deref()),
        ("stderr", check.stderr.as_deref()),
    ] {
        let Some(text) = text else {
            continue;
        };
        if vst3_validator_has_runtime_failure(&text.to_ascii_lowercase()) {
            return Err(format!("validator {label} includes runtime failure evidence").into());
        }
    }
    Ok(())
}

pub(super) fn validate_validator_passed_log_summary(
    check: &ValidatorCheck,
) -> Result<(), Box<dyn std::error::Error>> {
    let expected = (
        check
            .tests_passed
            .ok_or("validator passed test count is missing")?,
        check
            .tests_failed
            .ok_or("validator failed test count is missing")?,
    );
    for (label, text) in [
        ("stdout", check.stdout.as_deref()),
        ("stderr", check.stderr.as_deref()),
    ] {
        let Some(text) = text else {
            continue;
        };
        let Some(summary) = validator_test_summary(text) else {
            continue;
        };
        if summary != expected {
            return Err(format!(
                "validator {label} summary contradicts report counts: log passed={}, failed={}; report passed={}, failed={}",
                summary.0, summary.1, expected.0, expected.1
            )
            .into());
        }
    }
    Ok(())
}

pub(super) fn validate_release_validate_report(
    report: &ValidateReport,
) -> Result<(), Box<dyn std::error::Error>> {
    validate_validate_report_shape(report)?;
    validate_static_bundle_check_self_consistent(&report.static_check)?;
    validate_report_paths_self_consistent(report)?;
    if report.static_check.status != "ok" {
        return Err(format!(
            "static bundle check status is {}",
            report.static_check.status
        )
        .into());
    }
    validate_validator_check_self_consistent(&report.validator)?;
    if report.validator.status != "passed" {
        return Err(format!(
            "validator status is {}{}{}",
            report.validator.status,
            report
                .validator
                .reason
                .as_deref()
                .map(|reason| format!(" ({reason})"))
                .unwrap_or_default(),
            report
                .validator
                .error
                .as_deref()
                .map(|error| format!(": {error}"))
                .unwrap_or_default(),
        )
        .into());
    }
    Ok(())
}

pub(super) fn validate_static_validate_report(
    report: &ValidateReport,
) -> Result<(), Box<dyn std::error::Error>> {
    validate_validate_report_shape(report)?;
    validate_static_bundle_check_self_consistent(&report.static_check)?;
    validate_report_paths_self_consistent(report)?;
    validate_validator_check_self_consistent(&report.validator)?;
    if report.static_check.status != "ok" {
        return Err(format!(
            "static bundle check status is {}",
            report.static_check.status
        )
        .into());
    }
    if !matches!(
        report.validator.status.as_str(),
        "skipped" | "not_run" | "not_found"
    ) {
        return Err(format!(
            "static validate report must be static-only; validator status is {}",
            report.validator.status
        )
        .into());
    }
    Ok(())
}

pub(super) fn validate_static_bundle_binary_export_checks(
    check: &StaticBundleCheck,
) -> Result<(), Box<dyn std::error::Error>> {
    for export_check in &check.binary_exports {
        let expected = expected_binary_export_symbols(&export_check.platform).ok_or_else(|| {
            format!(
                "unknown binary export check platform `{}` for {}",
                export_check.platform, export_check.binary
            )
        })?;
        if let Some(inferred) = infer_validate_binary_platform(&export_check.binary)
            && inferred != export_check.platform
        {
            return Err(format!(
                "binary export check platform mismatch for {}: check says {}, binary path implies {inferred}",
                export_check.binary, export_check.platform
            )
            .into());
        }
        let missing_required = expected
            .iter()
            .copied()
            .filter(|symbol| {
                !export_check
                    .required_symbols
                    .iter()
                    .any(|item| item == symbol)
            })
            .collect::<Vec<_>>();
        if !missing_required.is_empty() {
            return Err(format!(
                "{} binary export check for {} has incomplete required symbol list: missing {}",
                export_check.platform,
                export_check.binary,
                missing_required.join(", ")
            )
            .into());
        }
        if export_check.status == "failed" {
            let missing = if export_check.missing_symbols.is_empty() {
                "<unknown>".to_string()
            } else {
                export_check.missing_symbols.join(", ")
            };
            return Err(format!(
                "{} binary export check failed for {}: missing {missing}",
                export_check.platform, export_check.binary
            )
            .into());
        }
        if export_check.status == "ok" {
            if export_check
                .tool
                .as_deref()
                .map(str::trim)
                .filter(|tool| !tool.is_empty())
                .is_none()
            {
                return Err(format!(
                    "{} binary export check for {} is ok but has no inspection tool",
                    export_check.platform, export_check.binary
                )
                .into());
            }
            let missing_found = expected
                .iter()
                .copied()
                .filter(|symbol| !export_check.found_symbols.iter().any(|item| item == symbol))
                .collect::<Vec<_>>();
            if !missing_found.is_empty() {
                return Err(format!(
                    "{} binary export check for {} is ok but did not record found symbols: {}",
                    export_check.platform,
                    export_check.binary,
                    missing_found.join(", ")
                )
                .into());
            }
            if !export_check.missing_symbols.is_empty() {
                return Err(format!(
                    "{} binary export check for {} is ok but still lists missing symbols: {}",
                    export_check.platform,
                    export_check.binary,
                    export_check.missing_symbols.join(", ")
                )
                .into());
            }
        } else if export_check.status == "skipped" {
            if export_check
                .error
                .as_deref()
                .map(str::trim)
                .filter(|error| !error.is_empty())
                .is_none()
            {
                return Err(format!(
                    "{} binary export check for {} was skipped without an explanation",
                    export_check.platform, export_check.binary
                )
                .into());
            }
        } else {
            return Err(format!(
                "{} binary export check for {} has unknown status `{}`",
                export_check.platform, export_check.binary, export_check.status
            )
            .into());
        }
    }
    Ok(())
}

pub(super) fn binary_export_check_proves_platform(
    check: &BinaryExportCheck,
    platform: &str,
) -> bool {
    check.platform == platform
        && check.status == "ok"
        && check.missing_symbols.is_empty()
        && expected_binary_export_symbols(platform).is_some_and(|expected| {
            expected.iter().all(|symbol| {
                check.required_symbols.iter().any(|item| item == symbol)
                    && check.found_symbols.iter().any(|item| item == symbol)
            })
        })
}

pub(super) fn strict_static_bundle_check_error(check: &StaticBundleCheck) -> Option<String> {
    if check.status != "ok" {
        return Some(format!(
            "strict validation requires static bundle check ok; actual status: {}",
            check.status
        ));
    }

    let platform_binaries = check
        .binaries
        .iter()
        .filter_map(|binary| {
            infer_validate_binary_platform(binary).and_then(|platform| {
                report_path_key(binary).map(|normalized| (binary, normalized, platform))
            })
        })
        .collect::<Vec<_>>();

    if platform_binaries.is_empty() {
        return Some(
            "strict validation requires at least one supported platform binary".to_string(),
        );
    }

    for (binary, normalized_binary, platform) in platform_binaries {
        let Some(export_check) = check.binary_exports.iter().find(|export_check| {
            export_check.platform == platform
                && report_path_key(&export_check.binary)
                    .is_some_and(|candidate| candidate == normalized_binary)
        }) else {
            return Some(format!(
                "strict validation requires binary export evidence for {binary} ({platform})"
            ));
        };

        if !binary_export_check_proves_platform(export_check, platform) {
            let detail = if export_check.status == "skipped" {
                export_check
                    .error
                    .as_deref()
                    .map(str::trim)
                    .filter(|error| !error.is_empty())
                    .unwrap_or("no reason recorded")
                    .to_string()
            } else if export_check.missing_symbols.is_empty() {
                format!("status {}", export_check.status)
            } else {
                format!(
                    "status {}; missing {}",
                    export_check.status,
                    export_check.missing_symbols.join(", ")
                )
            };
            return Some(format!(
                "strict validation requires ok binary export evidence for {binary} ({platform}); {detail}"
            ));
        }
    }

    None
}

pub(super) fn expected_binary_export_symbols(platform: &str) -> Option<&'static [&'static str]> {
    vesty_vst3_sys::required_binary_export_tool_symbols(platform)
}

pub(super) fn collect_validate_report_platforms(
    report: &ValidateReport,
    platforms: &mut Vec<&'static str>,
) {
    for binary in &report.static_check.binaries {
        if let Some(platform) = infer_validate_binary_platform(binary) {
            platforms.push(platform);
        }
    }
}

pub(super) fn validate_report_platforms(report: &ValidateReport) -> BTreeSet<&'static str> {
    report
        .static_check
        .binaries
        .iter()
        .filter_map(|binary| infer_validate_binary_platform(binary))
        .collect()
}

pub(super) fn infer_validate_binary_platform(binary: &str) -> Option<&'static str> {
    let binary = binary.replace('\\', "/");
    if binary.contains("/Contents/MacOS/") || binary.starts_with("Contents/MacOS/") {
        Some("macos")
    } else if binary.contains("/Contents/x86_64-win/") || binary.starts_with("Contents/x86_64-win/")
    {
        Some("windows-x64")
    } else if binary.contains("/Contents/x86_64-linux/")
        || binary.starts_with("Contents/x86_64-linux/")
    {
        Some("linux-x64")
    } else {
        None
    }
}

pub(super) fn validate_report_bundle_name(report: &ValidateReport) -> String {
    let bundle = report.bundle.replace('\\', "/");
    bundle
        .rsplit('/')
        .next()
        .filter(|name| !name.is_empty())
        .unwrap_or(bundle.as_str())
        .to_string()
}

pub(super) fn format_platform_coverage(platforms: &mut Vec<&'static str>) -> String {
    platforms.sort_unstable();
    platforms.dedup();
    if platforms.is_empty() {
        "unknown".to_string()
    } else {
        platforms.join(", ")
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub(super) enum SigningEvidencePlatform {
    Macos,
    Windows,
}

impl SigningEvidencePlatform {
    pub(super) fn label(self) -> &'static str {
        match self {
            SigningEvidencePlatform::Macos => "macOS",
            SigningEvidencePlatform::Windows => "Windows",
        }
    }
}

pub(super) fn signed_bundle_evidence_release_check(
    paths: &[Utf8PathBuf],
    required: bool,
) -> ReleaseCheckItem {
    if paths.is_empty() {
        return optional_release_check_missing(
            "signed bundle evidence",
            required,
            "pass one or more `--signed-bundle-evidence <log-or-signed-bundle>` paths",
        );
    }

    let mut failures = Vec::new();
    let mut platforms = BTreeSet::new();
    for path in paths {
        match signing_evidence_platforms(path) {
            Ok(found) => {
                if let Err(error) = validate_signing_artifact_path_platform(path, &found) {
                    failures.push(format!("{path}: {error}"));
                }
                platforms.extend(found);
            }
            Err(error) => failures.push(format!("{path}: {error}")),
        }
    }

    if !failures.is_empty() {
        return ReleaseCheckItem {
            name: "signed bundle evidence".to_string(),
            status: "failed".to_string(),
            value: failures.join("; "),
            hint: Some(
                "use codesign/signtool verification logs, or a macOS .vst3 bundle with Contents/_CodeSignature"
                    .to_string(),
            ),
        };
    }

    let missing_required_platforms = [
        (SigningEvidencePlatform::Macos, "macOS codesign"),
        (SigningEvidencePlatform::Windows, "Windows signtool"),
    ]
    .into_iter()
    .filter_map(|(platform, label)| (!platforms.contains(&platform)).then_some(label))
    .collect::<Vec<_>>();
    if required && !missing_required_platforms.is_empty() {
        return ReleaseCheckItem {
            name: "signed bundle evidence".to_string(),
            status: "failed".to_string(),
            value: format!(
                "missing signing coverage: {}",
                missing_required_platforms.join(", ")
            ),
            hint: Some(
                "strict release artifacts require both macOS codesign and Windows signtool verification evidence"
                    .to_string(),
            ),
        };
    }

    let platform_labels = platforms
        .iter()
        .map(|platform| platform.label())
        .collect::<Vec<_>>()
        .join(", ");
    ReleaseCheckItem {
        name: "signed bundle evidence".to_string(),
        status: "ok".to_string(),
        value: format!(
            "{} evidence path(s); platforms: {}",
            paths.len(),
            if platform_labels.is_empty() {
                "unknown"
            } else {
                &platform_labels
            }
        ),
        hint: None,
    }
}

pub(super) fn notarization_log_release_check(
    path: Option<&Utf8Path>,
    required: bool,
) -> ReleaseCheckItem {
    let Some(path) = path else {
        return optional_release_check_missing(
            "notarization log",
            required,
            "pass `--notarization-log <path>` containing accepted notarytool/stapler evidence",
        );
    };

    match notarization_evidence(path) {
        Ok(evidence) => {
            if let Err(error) = validate_notarization_artifact_path_platform(path) {
                return ReleaseCheckItem {
                    name: "notarization log".to_string(),
                    status: "failed".to_string(),
                    value: format!("{path}: {error}"),
                    hint: Some(
                        "notarization evidence should come from macOS notarytool and stapler logs"
                            .to_string(),
                    ),
                };
            }
            let mut missing = Vec::new();
            if !evidence.accepted {
                missing.push("accepted notarytool result");
            }
            if !evidence.stapled {
                missing.push("stapler success");
            }
            if required && !missing.is_empty() {
                return ReleaseCheckItem {
                    name: "notarization log".to_string(),
                    status: "failed".to_string(),
                    value: format!("missing notarization coverage: {}", missing.join(", ")),
                    hint: Some(
                        "strict release artifacts require both accepted notarytool output and stapler success evidence"
                            .to_string(),
                    ),
                };
            }
            ReleaseCheckItem {
                name: "notarization log".to_string(),
                status: "ok".to_string(),
                value: format!(
                    "{}; accepted={}; stapled={}",
                    path, evidence.accepted, evidence.stapled
                ),
                hint: None,
            }
        }
        Err(error) => ReleaseCheckItem {
            name: "notarization log".to_string(),
            status: "failed".to_string(),
            value: format!("{path}: {error}"),
            hint: Some(
                "include `xcrun notarytool submit --wait` accepted output and stapler output"
                    .to_string(),
            ),
        },
    }
}

pub(super) fn optional_release_check_missing(
    name: &str,
    required: bool,
    hint: impl Into<String>,
) -> ReleaseCheckItem {
    ReleaseCheckItem {
        name: name.to_string(),
        status: if required { "failed" } else { "skipped" }.to_string(),
        value: if required {
            "required evidence missing".to_string()
        } else {
            "not requested".to_string()
        },
        hint: Some(hint.into()),
    }
}
