// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BridgeErrorCode = "parse_error" | "unsupported_version" | "unsupported_type" | "validation_error" | "permission_denied" | "timeout" | "backpressure" | "host_rejected" | "plugin_faulted" | "state_conflict" | "internal_error";
