// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { BridgeErrorPayload } from "./BridgeErrorPayload";
import type { BridgeKind } from "./BridgeKind";
import type { BridgeLane } from "./BridgeLane";

export type BridgePacket = { v: number, session: string, seq: number, lane: BridgeLane, kind: BridgeKind, type: string, id?: string, replyTo?: string, payload?: JsonValue, error?: BridgeErrorPayload, flags?: Array<string>, };
