// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { BridgeErrorCode } from "./BridgeErrorCode";

export type BridgeErrorPayload = { code: BridgeErrorCode, message: string, details?: JsonValue, retryable: boolean, };
