// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeCapabilities } from "./BridgeCapabilities";
import type { ParamSpec } from "./ParamSpec";
import type { ParamValueSnapshot } from "./ParamValueSnapshot";
import type { PluginSnapshot } from "./PluginSnapshot";

export type BridgeReadyPayload = { protocolVersion: number, instanceId: string, editorSessionId: string, devMode: boolean, pluginName: string, vendor: string, capabilities: BridgeCapabilities, params: Array<ParamSpec>, paramValues: Array<ParamValueSnapshot>, snapshot: PluginSnapshot, };
