// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginFaultReport } from "./PluginFaultReport";

export type BridgeDiagnosticsSnapshot = { readyAcknowledged: boolean, subscriptionCount: number, subscriptions: Array<string>, pendingParamGestures: number, droppedParamGestures: number, pendingMeterTopics: number, fault?: PluginFaultReport, };
