// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BridgeCapabilities = { paramGestures: boolean, paramFormatParse: boolean, stateConfig: boolean, subscriptions: boolean, meterStream: boolean, reliableEvents: boolean, diagnostics: boolean, };
