// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamChangeSource } from "./ParamChangeSource";

export type ParamChangedEvent = { id: string, normalized: number, plain: number | null, display: string | null, source: ParamChangeSource, gestureId: string | null, revision: number, };
