// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamFlags } from "./ParamFlags";
import type { ParamKind } from "./ParamKind";
import type { ParamMidiMapping } from "./ParamMidiMapping";

export type ParamSpec = { id: string, name: string, kind: ParamKind, defaultNormalized: number, unit: string | null, stepCount: number | null, flags: ParamFlags, midiMappings: Array<ParamMidiMapping>, };
