// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type PluginSnapshot = { revision: number, paramsRevision: number, configRevision: number, uiRevision: number, config: JsonValue, uiState: JsonValue, };
