// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RtLogKind } from "./RtLogKind";
import type { RtLogLevel } from "./RtLogLevel";
import type { RtLogQueue } from "./RtLogQueue";

export type RtLogRecord = { sequence: number, level: RtLogLevel, kind: RtLogKind, queue?: RtLogQueue, otherQueueId?: number, dropped?: number, code?: number, value?: number, valueA?: number, valueB?: number, };
