import { defineConfig } from 'svedocs/config';

export default defineConfig({
  site: {
    name: 'Vesty',
    title: 'Vesty documentation',
    description: 'Build VST3 effects and instruments in Rust with explicit realtime boundaries and system WebView editors.'
  },
  content: {
    root: 'content',
    docs: 'content/docs',
    pages: 'content/pages'
  },
  theme: {
    defaultMode: 'dark',
    palette: {
      accent: '#e47a5f',
      neutral: 'stone'
    },
    fonts: {
      sans: 'ui-rounded, "SF Pro Rounded", "Avenir Next", "PingFang SC", "Microsoft YaHei", system-ui, sans-serif',
      display: 'ui-rounded, "SF Pro Rounded", "Avenir Next", "PingFang SC", "Microsoft YaHei", system-ui, sans-serif',
      mono: 'ui-monospace, "SFMono-Regular", "Cascadia Code", Menlo, Consolas, monospace'
    },
    radius: '4px',
    codeTheme: {
      light: 'github-light',
      dark: 'vesper'
    },
    brand: {
      label: 'VESTY',
      href: '/',
      logo: '/favicon.svg'
    },
    nav: [
      { label: 'Docs', labelKey: 'nav.docs', href: '/docs' },
      { label: 'Concepts', labelKey: 'nav.concepts', href: '/docs/concepts' },
      { label: 'Guides', labelKey: 'nav.guides', href: '/docs/guides' },
      { label: 'Reference', labelKey: 'nav.reference', href: '/docs/reference' }
    ],
    social: [
      { label: 'GitHub', href: 'https://github.com/orchiliao/vesty', external: true }
    ],
    footer: {
      text: 'Rust in the audio thread. Web tools in the editor.',
      links: [
        { label: 'Apache-2.0', href: 'https://github.com/orchiliao/vesty/blob/main/LICENSE-APACHE', external: true },
        { label: 'GitHub', href: 'https://github.com/orchiliao/vesty', external: true }
      ]
    },
    home: {
      primaryAction: { label: 'Start building', labelKey: 'home.primaryAction', href: '/docs/quick-start' },
      secondaryAction: { label: 'Read the architecture', labelKey: 'home.secondaryAction', href: '/docs/concepts/architecture' }
    }
  },
  search: {
    enabled: true,
    provider: 'local',
    scope: 'current'
  },
  ai: false,
  i18n: {
    defaultLocale: 'en',
    locales: [
      { code: 'en', label: 'English', hreflang: 'en', dir: 'ltr' },
      { code: 'zh', label: '简体中文', hreflang: 'zh-CN', dir: 'ltr' }
    ],
    messages: {
      en: {
        'nav.docs': 'Docs',
        'nav.concepts': 'Concepts',
        'nav.guides': 'Guides',
        'nav.reference': 'Reference',
        'footer.text': 'Rust on the audio thread. Web tools in the editor.',
        'home.primaryAction': 'Start building',
        'home.secondaryAction': 'Read the architecture',
        'landing.eyebrow': 'Rust-first framework for VST3 effects and instruments',
        'landing.description': 'Author VST3 effects and instruments in Rust, keep DSP inside an explicit realtime boundary, and build the editor with a directly embedded system WebView.',
        'landing.status': 'ALPHA / VST3 FIRST',
        'landing.docs': 'Open documentation',
        'landing.github': 'View source',
        'landing.commandLabel': 'Scaffold command',
        'landing.systemLabel': 'HOST / ADAPTER / KERNEL / EDITOR',
        'landing.mapLabel': 'VESTY AUTHORING PATH',
        'landing.scope': 'realtime boundary',
        'landing.scopeValue': 'explicit + testable',
        'landing.bridge': 'parameter identity',
        'landing.bridgeValue': 'stable + typed',
        'landing.editor': 'editor runtime',
        'landing.editorValue': 'wry system WebView',
        'landing.signalTitle': 'Native DSP and Web UI on opposite sides of the realtime boundary.',
        'landing.signalDescription': 'The VST3 adapter borrows host audio and events into Rust process contexts. The editor talks to the controller through typed JSBridge, never to the audio kernel.',
        'landing.stageHost': 'Host',
        'landing.stageHostDescription': 'Automation, events, transport',
        'landing.stageAdapter': 'VST3 adapter',
        'landing.stageAdapterDescription': 'ABI, buses, state, ordering',
        'landing.stageKernel': 'Audio kernel',
        'landing.stageKernelDescription': 'Borrowed buffers, bounded DSP',
        'landing.stageEditor': 'Web editor',
        'landing.stageEditorDescription': 'System WebView, typed bridge',
        'landing.explore': 'Complete the VST3 workflow',
        'landing.exploreDescription': 'Follow Vesty’s workflow from stable parameters and sample-accurate processing to a packaged plugin, validator reports, and DAW evidence.',
        'landing.cardStart': 'Complete plugin tutorial',
        'landing.cardStartDescription': 'Scaffold an effect, implement automation-safe DSP, test it, and package the VST3 bundle.',
        'landing.cardRealtime': 'Realtime process contract',
        'landing.cardRealtimeDescription': 'Keep allocation, locks, I/O, JSON, logging, and WebView calls outside process().',
        'landing.cardWeb': 'Host-authoritative Web UI',
        'landing.cardWebDescription': 'Initialize from ready.paramValues and send edit gestures through @vesty/plugin-ui.',
        'landing.cardShip': 'Package and validate',
        'landing.cardShipDescription': 'Check bundle metadata, exports, and manifests, then collect validator reports and evidence from real DAWs.',
        'landing.contract': 'THE CONTRACT',
        'landing.contractTitle': 'No allocation. No locks. No WebView in process().',
        'landing.contractDescription': 'Vesty resolves parameter handles before processing, borrows host buffers for one block, and moves UI communication outside the audio callback.',
        'landing.contractAction': 'Review realtime rules'
      },
      zh: {
        'nav.primary': '主导航',
        'nav.docs': '文档',
        'nav.concepts': '核心概念',
        'nav.guides': '开发指南',
        'nav.reference': '参考',
        'nav.documentation': '文档导航',
        'nav.footer': '页脚',
        'nav.social': '社交链接',
        'nav.mobile.open': '打开菜单',
        'nav.mobile.close': '关闭菜单',
        'nav.skipToContent': '跳到正文',
        'scope.group': '文档语言',
        'scope.locale': '语言',
        'scope.localeOptions': '语言选项',
        'scope.langShort': '语言',
        'search.trigger': '搜索',
        'search.dialog': '搜索文档',
        'search.query': '搜索关键词',
        'search.placeholder': '搜索 Vesty 文档',
        'search.results': '搜索结果',
        'search.loading': '正在搜索...',
        'search.loadingIndex': '正在加载搜索索引...',
        'search.indexError': '无法加载搜索索引。',
        'search.remoteFallback': '{error} 当前显示本地搜索结果。',
        'search.empty': '没有匹配的文档。',
        'search.fetchUnavailable': '当前环境无法发起网络请求。',
        'search.requestError': '搜索请求返回状态码 {status}。',
        'search.failed': '搜索失败。',
        'toc.label': '本页内容',
        'article.kind.doc': '文档',
        'article.kind.page': '页面',
        'article.breadcrumb': '面包屑',
        'article.updated': '更新于 {date}',
        'article.edit': '编辑此页',
        'article.previous': '上一页',
        'article.next': '下一页',
        'heading.anchor': '链接到此章节',
        'code.copy': '复制代码',
        'code.copied': '已复制',
        'code.copyDiff': '复制差异',
        'diff.label': '代码差异',
        'diff.aria': '{title}的代码差异',
        'diff.before': '修改前',
        'diff.after': '修改后',
        'tools.label': '页面工具',
        'tools.backToTop': '回到顶部',
        'theme.switch': '切换到{mode}主题',
        'theme.light': '浅色',
        'theme.dark': '深色',
        'footer.text': '音频线程运行 Rust，编辑器使用 Web 技术。',
        'home.primaryAction': '开始构建',
        'home.secondaryAction': '阅读架构',
        'home.features': '文档入口',
        'landing.eyebrow': '用 Rust 开发 VST3 效果器与乐器',
        'landing.description': '使用 Rust 编写 VST3 效果器与乐器，在明确的实时边界内运行 DSP，并通过直接嵌入的系统 WebView 构建编辑器。',
        'landing.status': 'ALPHA / VST3 优先',
        'landing.docs': '打开文档',
        'landing.github': '查看源码',
        'landing.commandLabel': '脚手架命令',
        'landing.systemLabel': '宿主 / 适配层 / 内核 / 编辑器',
        'landing.mapLabel': 'VESTY 开发路径',
        'landing.scope': '实时边界',
        'landing.scopeValue': '显式 + 可测试',
        'landing.bridge': '参数标识',
        'landing.bridgeValue': '稳定 + 强类型',
        'landing.editor': '编辑器运行时',
        'landing.editorValue': 'wry 系统 WebView',
        'landing.signalTitle': '原生 DSP 与 Web UI，分处实时边界两侧。',
        'landing.signalDescription': 'VST3 适配层把宿主音频缓冲区和事件借用给 Rust 处理上下文；编辑器通过强类型 JSBridge 与控制器通信，不直接接触音频内核。',
        'landing.stageHost': '宿主',
        'landing.stageHostDescription': '自动化、事件、传输',
        'landing.stageAdapter': 'VST3 适配层',
        'landing.stageAdapterDescription': 'ABI、总线、状态、事件排序',
        'landing.stageKernel': '音频内核',
        'landing.stageKernelDescription': '借用缓冲区、有界 DSP',
        'landing.stageEditor': 'Web 编辑器',
        'landing.stageEditorDescription': '系统 WebView、强类型桥接',
        'landing.explore': '完成整个 VST3 开发流程',
        'landing.exploreDescription': '沿着 Vesty 的实际开发流程，从稳定的参数标识与采样级精确处理，走到插件打包、Steinberg validator 报告和真实 DAW 验证。',
        'landing.cardStart': '完整插件教程',
        'landing.cardStartDescription': '创建效果器、实现支持自动化的 DSP、完成测试，并打包 VST3 插件。',
        'landing.cardRealtime': '实时处理契约',
        'landing.cardRealtimeDescription': '不要在 process() 中分配内存、加锁，也不要执行 I/O、JSON、普通日志或 WebView 调用。',
        'landing.cardWeb': '以宿主状态为准的 Web UI',
        'landing.cardWebDescription': '使用 ready.paramValues 初始化界面，并通过 @vesty/plugin-ui 发送参数编辑手势。',
        'landing.cardShip': '打包与验证',
        'landing.cardShipDescription': '检查插件包元数据、导出符号和参数清单，再收集 Steinberg validator 报告与真实 DAW 证据。',
        'landing.contract': '核心契约',
        'landing.contractTitle': 'process() 中不分配、不加锁、不调用 WebView。',
        'landing.contractDescription': 'Vesty 在处理前解析参数句柄，每个音频块只借用宿主缓冲区，并把所有 UI 通信移出音频回调。',
        'landing.contractAction': '检查实时规则',
        'error.notFound.title': '页面未找到',
        'error.notFound.description': 'Vesty 文档中没有找到你要访问的页面。',
        'error.generic.title': '出现了问题',
        'error.generic.description': '页面暂时无法显示，你仍然可以通过文档导航继续浏览。',
        'error.status': '错误 {status}',
        'error.home': '首页',
        'error.docs': '文档',
        'render.label': '渲染问题',
        'render.title': '此章节无法显示',
        'render.message': '文档的这一部分渲染失败，其余内容仍然可用。',
        'render.details': '技术详情',
        'render.tryAgain': '重试',
        'render.reload': '重新加载页面',
        'render.docsHome': '文档首页',
        'render.layout.label': '布局问题',
        'render.layout.title': '页面布局无法显示',
        'render.layout.message': '布局组件渲染失败，默认站点框架仍然可用。',
        'render.header.label': '页眉问题',
        'render.header.title': '页眉无法显示',
        'render.header.message': '正文仍然可用。你可以重试页眉，或使用正文中的链接继续浏览。',
        'render.ask.label': 'AI 问答问题',
        'render.ask.title': 'AI 问答无法显示',
        'render.ask.message': '文章仍然可用，需要时可以重试 AI 问答。',
        'render.tools.label': '页面工具问题',
        'render.tools.title': '页面工具无法显示',
        'render.tools.message': '页面工具渲染失败，但不影响文档正文。',
        'render.footer.label': '页脚问题',
        'render.footer.title': '页脚无法显示',
        'render.footer.message': '页脚链接渲染失败，上方正文仍然可用。',
        'render.page.label': '页面渲染问题',
        'render.page.title': '此页面无法显示',
        'render.page.message': '页面内容渲染失败。你可以重试此区域或重新加载页面。',
        'render.article.label': '文章渲染问题',
        'render.article.title': '此文章无法显示',
        'render.article.message': '文章内容渲染失败，导航和页面工具仍然可用。',
        'render.docs.label': '文档布局问题',
        'render.docs.title': '文档布局无法显示',
        'render.docs.message': '布局组件渲染失败。你可以重试此区域，或使用顶部导航继续浏览。',
        'render.home.label': '首页内容问题',
        'render.home.title': '首页内容无法显示',
        'render.home.message': '首页内容渲染失败，站点的其他部分仍然可用。',
        'render.error.label': '错误页面问题',
        'render.error.title': '错误页面无法显示',
        'render.error.message': '自定义错误页面渲染失败，当前显示默认恢复界面。',
        'render.custom.label': '自定义布局问题',
        'render.custom.title': '自定义布局无法显示',
        'render.custom.message': '自定义页面布局渲染失败。路由已正常加载，请修复组件后重试。',
        'render.navigation.label': '导航问题',
        'render.navigation.title': '导航无法显示',
        'render.navigation.message': '正文仍然可用。你可以重试导航区域，或使用顶部导航继续浏览。',
        'render.outline.label': '目录问题',
        'render.outline.title': '本页目录无法显示',
        'render.outline.message': '本页目录渲染失败，但文章正文仍然可用。',
        'render.errorUi.label': '错误边界问题',
        'render.errorUi.title': '错误界面无法显示',
        'render.errorUi.message': '自定义错误组件渲染失败，当前显示默认恢复界面。'
      }
    }
  },
  source: {
    editBaseUrl: 'https://github.com/orchiliao/vesty/edit/main/docs'
  },
  checks: {
    assets: true,
    externalLinks: false,
    translations: true
  },
  seo: {
    sitemap: true,
    robots: true,
    defaultAuthor: 'Vesty contributors',
    ogImage: {
      template: 'default',
      format: 'svg',
      outDir: 'static/og',
      renderer: 'svg'
    }
  }
});
