use crate::*;

pub fn generated_bindings_interface_skeleton_module(
    plan: &GeneratedBindingsPlan,
    surface: &GeneratedBindingsSurface,
) -> String {
    let mut module = String::new();
    module.push_str("// @generated by ");
    module.push_str(GENERATED_BINDINGS_INTERFACE_SKELETON_GENERATOR);
    module.push('\n');
    module.push_str("// This is a deterministic COM interface skeleton for Vesty's reserved VST3 SDK generated-bindings backend.\n");
    module.push_str("// It emits repr(C) interface/vtable callback field layout seeds plus method-surface/slot-order/signature-intent/vtable-slot-seed/callback-type-alias-seed/interface-id/query-interface-plan/com-object-interface exposure/object-identity/object-dispatch/factory-class/binary-export-symbol metadata and pure IID/dispatch lookup helpers,\n");
    module.push_str(
        "// but intentionally omits callable implementations and full COM binding glue.\n",
    );
    module.push_str(
        "#![allow(dead_code, non_camel_case_types, non_snake_case, non_upper_case_globals)]\n\n",
    );
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct HeaderInput {\n");
    module.push_str("    pub path: &'static str,\n");
    module.push_str("    pub size: u64,\n");
    module.push_str("    pub sha256: &'static str,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct BindingSymbol {\n");
    module.push_str("    pub name: &'static str,\n");
    module.push_str("    pub kind: &'static str,\n");
    module.push_str("    pub header: &'static str,\n");
    module.push_str("    pub purpose: &'static str,\n");
    module.push_str("    pub symbol_present: bool,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct InterfaceMethod {\n");
    module.push_str("    pub slot: usize,\n");
    module.push_str("    pub interface: &'static str,\n");
    module.push_str("    pub name: &'static str,\n");
    module.push_str("    pub purpose: &'static str,\n");
    module.push_str("    pub realtime: bool,\n");
    module.push_str("    pub signature: &'static str,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct InterfaceCallbackType {\n");
    module.push_str("    pub interface: &'static str,\n");
    module.push_str("    pub method: &'static str,\n");
    module.push_str("    pub callback_type: &'static str,\n");
    module.push_str("    pub signature: &'static str,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct InterfaceVTableFieldOffset {\n");
    module.push_str("    pub interface: &'static str,\n");
    module.push_str("    pub field: &'static str,\n");
    module.push_str("    pub callback_type: &'static str,\n");
    module.push_str("    pub offset: usize,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct InterfaceVTableSlot {\n");
    module.push_str("    pub local_slot: usize,\n");
    module.push_str("    pub global_slot: usize,\n");
    module.push_str("    pub interface: &'static str,\n");
    module.push_str("    pub method: &'static str,\n");
    module.push_str("    pub field: &'static str,\n");
    module.push_str("    pub callback_type: &'static str,\n");
    module.push_str("    pub signature: &'static str,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct InterfaceId {\n");
    module.push_str("    pub interface: &'static str,\n");
    module.push_str("    pub iid_const: &'static str,\n");
    module.push_str("    pub uid_words: [u32; 4],\n");
    module.push_str("    pub source: &'static str,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct QueryInterfaceEntry {\n");
    module.push_str("    pub interface: &'static str,\n");
    module.push_str("    pub iid_const: &'static str,\n");
    module.push_str("    pub inherits_funknown: bool,\n");
    module.push_str("    pub implementation: &'static str,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct ComObjectInterface {\n");
    module.push_str("    pub object: &'static str,\n");
    module.push_str("    pub interface: &'static str,\n");
    module.push_str("    pub iid_const: &'static str,\n");
    module.push_str("    pub exposure: &'static str,\n");
    module.push_str("    pub source: &'static str,\n");
    module.push_str("    pub required: bool,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct ComObjectIdentityPlan {\n");
    module.push_str("    pub object: &'static str,\n");
    module.push_str("    pub root_interface: &'static str,\n");
    module.push_str("    pub root_iid_const: &'static str,\n");
    module.push_str("    pub funknown_identity: &'static str,\n");
    module.push_str("    pub refcount_policy: &'static str,\n");
    module.push_str("    pub unknown_iid_result: &'static str,\n");
    module.push_str("    pub null_object_pointer_result: &'static str,\n");
    module.push_str("    pub source: &'static str,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct ComObjectQueryInterfaceDispatchEntry {\n");
    module.push_str("    pub object: &'static str,\n");
    module.push_str("    pub interface: &'static str,\n");
    module.push_str("    pub iid_const: &'static str,\n");
    module.push_str("    pub root_interface: &'static str,\n");
    module.push_str("    pub returns_same_identity: bool,\n");
    module.push_str("    pub success_result: &'static str,\n");
    module.push_str("    pub add_ref_on_success: bool,\n");
    module.push_str("    pub implementation: &'static str,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct FactoryExportPlan {\n");
    module.push_str("    pub factory_object: &'static str,\n");
    module.push_str("    pub factory_interface: &'static str,\n");
    module.push_str("    pub factory_iid_const: &'static str,\n");
    module.push_str("    pub class_count: usize,\n");
    module.push_str("    pub count_classes_result: &'static str,\n");
    module.push_str("    pub get_factory_info_source: &'static str,\n");
    module.push_str("    pub source: &'static str,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct FactoryClassPlan {\n");
    module.push_str("    pub class_kind: &'static str,\n");
    module.push_str("    pub class_index: usize,\n");
    module.push_str("    pub class_object: &'static str,\n");
    module.push_str("    pub root_interface: &'static str,\n");
    module.push_str("    pub root_iid_const: &'static str,\n");
    module.push_str("    pub category: &'static str,\n");
    module.push_str("    pub name_source: &'static str,\n");
    module.push_str("    pub cid_source: &'static str,\n");
    module.push_str("    pub cid_policy: &'static str,\n");
    module.push_str("    pub cardinality: &'static str,\n");
    module.push_str("    pub get_class_info_result: &'static str,\n");
    module.push_str("    pub invalid_class_index_result: &'static str,\n");
    module.push_str("    pub create_instance_object: &'static str,\n");
    module.push_str("    pub create_instance_root_interface: &'static str,\n");
    module.push_str("    pub create_instance_root_iid_const: &'static str,\n");
    module.push_str("    pub unknown_cid_result: &'static str,\n");
    module.push_str("    pub construction_failure_result: &'static str,\n");
    module.push_str("    pub requested_iid_dispatch: &'static str,\n");
    module.push_str("    pub source: &'static str,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct ModuleExportPlan {\n");
    module.push_str("    pub symbol: &'static str,\n");
    module.push_str("    pub platforms: &'static str,\n");
    module.push_str("    pub signature: &'static str,\n");
    module.push_str("    pub purpose: &'static str,\n");
    module.push_str("    pub implementation: &'static str,\n");
    module.push_str("    pub return_policy: &'static str,\n");
    module.push_str("    pub generated_callable: bool,\n");
    module.push_str("    pub source: &'static str,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct BinaryExportSymbolPlan {\n");
    module.push_str("    pub platform: &'static str,\n");
    module.push_str("    pub binary_format: &'static str,\n");
    module.push_str("    pub symbol: &'static str,\n");
    module.push_str("    pub tool_symbol: &'static str,\n");
    module.push_str("    pub inspection_tool: &'static str,\n");
    module.push_str("    pub required: bool,\n");
    module.push_str("    pub verified_by_generated_bindings: bool,\n");
    module.push_str("    pub source: &'static str,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct BinaryExportInspectionToolPlan {\n");
    module.push_str("    pub platform: &'static str,\n");
    module.push_str("    pub program: &'static str,\n");
    module.push_str("    pub args: &'static [&'static str],\n");
    module.push_str("}\n\n");
    module.push_str("pub const GENERATOR: &str = ");
    module.push_str(&rust_string_literal(
        GENERATED_BINDINGS_INTERFACE_SKELETON_GENERATOR,
    ));
    module.push_str(";\n");
    module.push_str("pub const PLAN_GENERATOR: &str = ");
    module.push_str(&rust_string_literal(&plan.generator));
    module.push_str(";\n");
    module.push_str("pub const SURFACE_GENERATOR: &str = ");
    module.push_str(&rust_string_literal(&surface.generator));
    module.push_str(";\n");
    module.push_str("pub const STATUS: &str = \"interface-skeleton\";\n");
    module.push_str("pub const PLAN_STATUS: &str = ");
    module.push_str(&rust_string_literal(&plan.status));
    module.push_str(";\n");
    module.push_str("pub const SURFACE_STATUS: &str = ");
    module.push_str(&rust_string_literal(&surface.status));
    module.push_str(";\n");
    module.push_str("pub const INTERFACE_SKELETON_GENERATED: bool = true;\n");
    module.push_str("pub const BINDINGS_GENERATED: bool = false;\n");
    module.push_str("pub const FULL_COM_BINDINGS_GENERATED: bool = false;\n");
    module.push_str("pub const STEINBERG_VST3_SDK_BASELINE: &str = ");
    module.push_str(&rust_string_literal(&plan.steinberg_sdk_baseline));
    module.push_str(";\n");
    module.push_str("pub const UPSTREAM_VST3_CRATE_BASELINE: &str = ");
    module.push_str(&rust_string_literal(&plan.upstream_vst3_crate_baseline));
    module.push_str(";\n");
    module.push_str("pub const ACTIVE_BACKEND: &str = ");
    module.push_str(&rust_string_literal(&plan.active_backend));
    module.push_str(";\n");
    module.push_str("pub const REQUIRED_HEADER_COUNT: usize = ");
    module.push_str(&plan.header_manifest.headers.len().to_string());
    module.push_str(";\n");
    module.push_str("pub const MISSING_HEADER_COUNT: usize = ");
    module.push_str(&plan.header_manifest.missing_headers.len().to_string());
    module.push_str(";\n");
    module.push_str("pub const SURFACE_SYMBOL_COUNT: usize = ");
    module.push_str(&surface.symbols.len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub const INTERFACE_ID_COUNT: usize = ");
    module.push_str(&GENERATED_BINDINGS_INTERFACE_IDS.len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub const QUERY_INTERFACE_ENTRY_COUNT: usize = ");
    module.push_str(&GENERATED_BINDINGS_INTERFACE_IDS.len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub const COM_OBJECT_COUNT: usize = ");
    module.push_str(&GENERATED_BINDINGS_COM_OBJECTS.len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub const COM_OBJECT_INTERFACE_COUNT: usize = ");
    module.push_str(&GENERATED_BINDINGS_COM_OBJECT_INTERFACES.len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub const COM_OBJECT_IDENTITY_PLAN_COUNT: usize = ");
    module.push_str(&GENERATED_BINDINGS_COM_OBJECT_IDENTITIES.len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub const COM_OBJECT_QUERY_INTERFACE_DISPATCH_ENTRY_COUNT: usize = ");
    module.push_str(
        &(GENERATED_BINDINGS_COM_OBJECT_IDENTITIES.len()
            + GENERATED_BINDINGS_COM_OBJECT_INTERFACES.len())
        .to_string(),
    );
    module.push_str(";\n\n");
    module.push_str("pub const FACTORY_EXPORT_PLAN_COUNT: usize = 1;\n\n");
    module.push_str("pub const FACTORY_CLASS_PLAN_COUNT: usize = ");
    module.push_str(&GENERATED_BINDINGS_FACTORY_CLASS_PLANS.len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub const MODULE_EXPORT_PLAN_COUNT: usize = ");
    module.push_str(&GENERATED_BINDINGS_MODULE_EXPORT_PLANS.len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub const BINARY_EXPORT_SYMBOL_PLAN_COUNT: usize = ");
    module.push_str(
        &GENERATED_BINDINGS_BINARY_EXPORT_SYMBOL_PLANS
            .len()
            .to_string(),
    );
    module.push_str(";\n\n");
    module.push_str("pub const BINARY_EXPORT_INSPECTION_TOOL_PLAN_COUNT: usize = ");
    module.push_str(&BINARY_EXPORT_INSPECTION_TOOL_PLANS.len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub const INTERFACE_METHOD_COUNT: usize = ");
    module.push_str(&GENERATED_BINDINGS_INTERFACE_METHODS.len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub const INTERFACE_VTABLE_SLOT_COUNT: usize = ");
    module.push_str(&GENERATED_BINDINGS_INTERFACE_METHODS.len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub const INTERFACE_VTABLE_FIELD_COUNT: usize = ");
    module.push_str(&GENERATED_BINDINGS_INTERFACE_METHODS.len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub const INTERFACE_VTABLE_FIELD_OFFSET_COUNT: usize = ");
    module.push_str(&GENERATED_BINDINGS_INTERFACE_METHODS.len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub const INTERFACE_CALLBACK_TYPE_COUNT: usize = ");
    module.push_str(&GENERATED_BINDINGS_INTERFACE_METHODS.len().to_string());
    module.push_str(";\n\n");
    module
        .push_str("pub const INTERFACE_METHOD_SLOT_SCOPE: &str = \"per-interface-order-audit\";\n");
    module.push_str(
        "pub const INTERFACE_METHOD_SIGNATURE_SCOPE: &str = \"signature-intent-audit\";\n\n",
    );
    module.push_str("pub const INTERFACE_VTABLE_SLOT_SCOPE: &str = \"per-interface-local-vtable-seed-audit\";\n\n");
    module.push_str("pub const INTERFACE_VTABLE_GLOBAL_SLOT_SCOPE: &str = \"com-vtable-global-slot-seed-audit\";\n\n");
    module.push_str("pub const INTERFACE_VTABLE_SLOT_LOOKUP_SCOPE: &str = \"pure-vtable-slot-lookup-seed-audit\";\n\n");
    module.push_str(
        "pub const INTERFACE_VTABLE_FIELD_SCOPE: &str = \"repr-c-vtable-callback-field-layout-seed-audit\";\n\n",
    );
    module.push_str(
        "pub const INTERFACE_VTABLE_FIELD_OFFSET_SCOPE: &str = \"repr-c-vtable-callback-field-offset-fingerprint-audit\";\n\n",
    );
    module.push_str("pub const INTERFACE_VTABLE_FIELD_OFFSET_LOOKUP_SCOPE: &str = \"pure-vtable-field-offset-lookup-seed-audit\";\n\n");
    module.push_str(
        "pub const INTERFACE_CALLBACK_TYPE_SCOPE: &str = \"callback-type-alias-seed-audit\";\n\n",
    );
    module.push_str(
        "pub const INTERFACE_ID_SCOPE: &str = \"upstream-vst3-interface-iid-audit\";\n\n",
    );
    module.push_str(
        "pub const QUERY_INTERFACE_ENTRY_SCOPE: &str = \"query-interface-dispatch-plan-audit\";\n\n",
    );
    module.push_str(
        "pub const QUERY_INTERFACE_IID_LOOKUP_SCOPE: &str = \"pure-iid-dispatch-lookup-seed-audit\";\n\n",
    );
    module.push_str(
        "pub const COM_OBJECT_INTERFACE_SCOPE: &str = \"vesty-com-object-interface-exposure-plan-audit\";\n\n",
    );
    module.push_str(
        "pub const COM_OBJECT_IDENTITY_PLAN_SCOPE: &str = \"vesty-com-object-funknown-identity-plan-audit\";\n\n",
    );
    module.push_str(
        "pub const COM_OBJECT_QUERY_INTERFACE_DISPATCH_SCOPE: &str = \"vesty-com-object-query-interface-dispatch-plan-audit\";\n\n",
    );
    module.push_str(
        "pub const FACTORY_EXPORT_PLAN_SCOPE: &str = \"vesty-factory-export-plan-audit\";\n\n",
    );
    module.push_str(
        "pub const FACTORY_CLASS_PLAN_SCOPE: &str = \"vesty-factory-class-plan-audit\";\n\n",
    );
    module.push_str(
        "pub const MODULE_EXPORT_PLAN_SCOPE: &str = \"vesty-module-export-plan-audit\";\n\n",
    );
    module.push_str(
        "pub const BINARY_EXPORT_SYMBOL_PLAN_SCOPE: &str = \"vesty-binary-export-symbol-plan-audit\";\n\n",
    );
    module.push_str(
        "pub const BINARY_EXPORT_INSPECTION_TOOL_PLAN_SCOPE: &str = \"vesty-binary-export-inspection-tool-plan-audit\";\n\n",
    );
    module.push_str("pub const BINARY_EXPORT_SYMBOL_REQUIREMENT_HELPERS_GENERATED: bool = true;\n");
    module.push_str("pub const BINARY_EXPORT_SYMBOL_INSPECTION_GENERATED: bool = false;\n\n");
    module.push_str("pub type int16 = i16;\n");
    module.push_str("pub type int32 = i32;\n");
    module.push_str("pub type int64 = i64;\n");
    module.push_str("pub type uint32 = u32;\n");
    module.push_str("pub type TResult = i32;\n");
    module.push_str("pub type char16 = u16;\n");
    module.push_str("pub type TBool = u8;\n");
    module.push_str("pub type TChar = u16;\n");
    module.push_str("pub type FIDString = *const std::os::raw::c_char;\n");
    module.push_str("pub type CString = *const std::os::raw::c_char;\n");
    module.push_str("pub type TCharConstPtr = *const TChar;\n");
    module.push_str("pub type AttrID = FIDString;\n");
    module.push_str("pub type ParamID = u32;\n");
    module.push_str("pub type ParamValue = f64;\n");
    module.push_str("pub type CtrlNumber = int16;\n");
    module.push_str("pub type IoMode = int32;\n");
    module.push_str("pub type MediaType = int32;\n");
    module.push_str("pub type BusDirection = int32;\n");
    module.push_str("pub type SpeakerArrangement = u64;\n");
    module.push_str("pub type UnitID = int32;\n");
    module.push_str("pub type ProgramListID = int32;\n");
    module.push_str("pub type NoteExpressionTypeID = uint32;\n");
    module.push_str("pub type NoteExpressionValue = f64;\n");
    module.push_str("pub type PClassInfo = std::ffi::c_void;\n");
    module.push_str("pub type ViewRect = std::ffi::c_void;\n");
    module.push_str("pub type BusInfo = std::ffi::c_void;\n");
    module.push_str("pub type RoutingInfo = std::ffi::c_void;\n");
    module.push_str("pub type ProcessSetup = std::ffi::c_void;\n");
    module.push_str("pub type ProcessData = std::ffi::c_void;\n");
    module.push_str("pub type ParameterInfo = std::ffi::c_void;\n");
    module.push_str("pub type Event = std::ffi::c_void;\n");
    module.push_str("pub type UnitInfo = std::ffi::c_void;\n");
    module.push_str("pub type ProgramListInfo = std::ffi::c_void;\n");
    module.push_str("pub type NoteExpressionTypeInfo = std::ffi::c_void;\n");
    module.push_str("pub type PhysicalUIMapList = std::ffi::c_void;\n");
    module.push_str("pub type String128 = *mut TChar;\n\n");
    module.push_str("pub const TUID_BYTE_LEN: usize = 16;\n");
    module.push_str("pub const FUNKNOWN_VTABLE_ENTRIES: usize = 3;\n");
    module.push_str("pub const kResultOk: TResult = 0;\n");
    module.push_str("pub const kInvalidArgument: TResult = 2;\n");
    module.push_str("pub const kNotImplemented: TResult = 3;\n");
    module.push_str("#[cfg(windows)]\n");
    module.push_str("pub const kNoInterface: TResult = 0x80004002u32 as i32;\n");
    module.push_str("#[cfg(not(windows))]\n");
    module.push_str("pub const kNoInterface: TResult = -1;\n\n");
    module.push_str("#[repr(C)]\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct TUID {\n");
    module.push_str("    pub data: [std::os::raw::c_char; TUID_BYTE_LEN],\n");
    module.push_str("}\n\n");
    module.push_str("impl TUID {\n");
    module.push_str("    pub const ZERO: Self = Self { data: [0; TUID_BYTE_LEN] };\n");
    module.push_str("}\n\n");
    module.push_str("pub const fn iid_from_words(a: u32, b: u32, c: u32, d: u32) -> TUID {\n");
    module.push_str("    #[cfg(target_os = \"windows\")]\n");
    module.push_str("    let data = [\n");
    module.push_str("        ((a & 0x000000FF) >> 0) as std::os::raw::c_char,\n");
    module.push_str("        ((a & 0x0000FF00) >> 8) as std::os::raw::c_char,\n");
    module.push_str("        ((a & 0x00FF0000) >> 16) as std::os::raw::c_char,\n");
    module.push_str("        ((a & 0xFF000000) >> 24) as std::os::raw::c_char,\n");
    module.push_str("        ((b & 0x00FF0000) >> 16) as std::os::raw::c_char,\n");
    module.push_str("        ((b & 0xFF000000) >> 24) as std::os::raw::c_char,\n");
    module.push_str("        ((b & 0x000000FF) >> 0) as std::os::raw::c_char,\n");
    module.push_str("        ((b & 0x0000FF00) >> 8) as std::os::raw::c_char,\n");
    module.push_str("        ((c & 0xFF000000) >> 24) as std::os::raw::c_char,\n");
    module.push_str("        ((c & 0x00FF0000) >> 16) as std::os::raw::c_char,\n");
    module.push_str("        ((c & 0x0000FF00) >> 8) as std::os::raw::c_char,\n");
    module.push_str("        ((c & 0x000000FF) >> 0) as std::os::raw::c_char,\n");
    module.push_str("        ((d & 0xFF000000) >> 24) as std::os::raw::c_char,\n");
    module.push_str("        ((d & 0x00FF0000) >> 16) as std::os::raw::c_char,\n");
    module.push_str("        ((d & 0x0000FF00) >> 8) as std::os::raw::c_char,\n");
    module.push_str("        ((d & 0x000000FF) >> 0) as std::os::raw::c_char,\n");
    module.push_str("    ];\n");
    module.push_str("    #[cfg(not(target_os = \"windows\"))]\n");
    module.push_str("    let data = [\n");
    module.push_str("        ((a & 0xFF000000) >> 24) as std::os::raw::c_char,\n");
    module.push_str("        ((a & 0x00FF0000) >> 16) as std::os::raw::c_char,\n");
    module.push_str("        ((a & 0x0000FF00) >> 8) as std::os::raw::c_char,\n");
    module.push_str("        ((a & 0x000000FF) >> 0) as std::os::raw::c_char,\n");
    module.push_str("        ((b & 0xFF000000) >> 24) as std::os::raw::c_char,\n");
    module.push_str("        ((b & 0x00FF0000) >> 16) as std::os::raw::c_char,\n");
    module.push_str("        ((b & 0x0000FF00) >> 8) as std::os::raw::c_char,\n");
    module.push_str("        ((b & 0x000000FF) >> 0) as std::os::raw::c_char,\n");
    module.push_str("        ((c & 0xFF000000) >> 24) as std::os::raw::c_char,\n");
    module.push_str("        ((c & 0x00FF0000) >> 16) as std::os::raw::c_char,\n");
    module.push_str("        ((c & 0x0000FF00) >> 8) as std::os::raw::c_char,\n");
    module.push_str("        ((c & 0x000000FF) >> 0) as std::os::raw::c_char,\n");
    module.push_str("        ((d & 0xFF000000) >> 24) as std::os::raw::c_char,\n");
    module.push_str("        ((d & 0x00FF0000) >> 16) as std::os::raw::c_char,\n");
    module.push_str("        ((d & 0x0000FF00) >> 8) as std::os::raw::c_char,\n");
    module.push_str("        ((d & 0x000000FF) >> 0) as std::os::raw::c_char,\n");
    module.push_str("    ];\n");
    module.push_str("    TUID { data }\n");
    module.push_str("}\n\n");
    for spec in GENERATED_BINDINGS_INTERFACE_IDS {
        push_interface_iid_const(&mut module, spec);
    }
    module.push('\n');
    module.push_str("pub type FUnknownQueryInterface = unsafe extern \"system\" fn(\n");
    module.push_str("    this: *mut FUnknown,\n");
    module.push_str("    iid: *const TUID,\n");
    module.push_str("    obj: *mut *mut std::ffi::c_void,\n");
    module.push_str(") -> TResult;\n");
    module.push_str(
        "pub type FUnknownAddRef = unsafe extern \"system\" fn(this: *mut FUnknown) -> uint32;\n",
    );
    module.push_str("pub type FUnknownRelease = unsafe extern \"system\" fn(this: *mut FUnknown) -> uint32;\n\n");
    module.push_str(
        "// Callback type aliases are audit seeds for the future generated-headers emitter.\n",
    );
    module.push_str("// VTable structs below intentionally contain callback field layout seeds but no callback implementations.\n");
    for method in GENERATED_BINDINGS_INTERFACE_METHODS
        .iter()
        .filter(|method| method.interface != "FUnknown")
    {
        push_interface_callback_type_alias(&mut module, method);
    }
    module.push('\n');
    module.push_str("#[repr(C)]\n");
    module.push_str("#[derive(Clone, Copy)]\n");
    module.push_str("pub struct FUnknownVTable {\n");
    module.push_str("    pub queryInterface: FUnknownQueryInterface,\n");
    module.push_str("    pub addRef: FUnknownAddRef,\n");
    module.push_str("    pub release: FUnknownRelease,\n");
    module.push_str("}\n\n");
    module.push_str("#[repr(C)]\n");
    module.push_str("#[derive(Clone, Copy)]\n");
    module.push_str("pub struct FUnknown {\n");
    module.push_str("    pub vtable: *const FUnknownVTable,\n");
    module.push_str("}\n\n");

    for symbol in surface
        .symbols
        .iter()
        .filter(|symbol| symbol.kind == "interface" && symbol.name != "FUnknown")
    {
        module.push_str("#[repr(C)]\n");
        module.push_str("#[derive(Clone, Copy)]\n");
        module.push_str("pub struct ");
        module.push_str(&symbol.name);
        module.push_str("VTable {\n");
        module.push_str("    pub unknown: FUnknownVTable,\n");
        let methods = interface_methods(symbol.name.as_str());
        for method in &methods {
            push_interface_vtable_field(&mut module, method);
        }
        module.push_str("}\n\n");
        module.push_str("pub const ");
        module.push_str(&interface_methods_const_name(symbol.name.as_str()));
        module.push_str(": &[InterfaceMethod] = &[\n");
        for (slot, method) in methods.iter().enumerate() {
            push_interface_method_record(&mut module, method, slot);
        }
        module.push_str("];\n\n");
        module.push_str("pub const ");
        module.push_str(&interface_vtable_slots_const_name(symbol.name.as_str()));
        module.push_str(": &[InterfaceVTableSlot] = &[\n");
        for (slot, method) in methods.iter().enumerate() {
            push_interface_vtable_slot_record(&mut module, method, slot);
        }
        module.push_str("];\n\n");
        module.push_str("pub const ");
        module.push_str(&interface_callback_types_const_name(symbol.name.as_str()));
        module.push_str(": &[InterfaceCallbackType] = &[\n");
        for method in &methods {
            push_interface_callback_type_record(&mut module, method);
        }
        module.push_str("];\n\n");
        module.push_str("pub const ");
        module.push_str(&interface_vtable_field_offsets_const_name(
            symbol.name.as_str(),
        ));
        module.push_str(": &[InterfaceVTableFieldOffset] = &[\n");
        for method in &methods {
            push_interface_vtable_field_offset_record(&mut module, method);
        }
        module.push_str("];\n\n");
        module.push_str("pub const ");
        module.push_str(&interface_method_count_const_name(symbol.name.as_str()));
        module.push_str(": usize = ");
        module.push_str(&methods.len().to_string());
        module.push_str(";\n\n");
        module.push_str("#[repr(C)]\n");
        module.push_str("#[derive(Clone, Copy)]\n");
        module.push_str("pub struct ");
        module.push_str(&symbol.name);
        module.push_str(" {\n");
        module.push_str("    pub vtable: *const ");
        module.push_str(&symbol.name);
        module.push_str("VTable,\n");
        module.push_str("}\n\n");
    }

    module.push_str("pub const INTERFACE_SKELETON_TYPES: &[&str] = &[\n");
    module.push_str("    \"FUnknown\",\n");
    for symbol in surface
        .symbols
        .iter()
        .filter(|symbol| symbol.kind == "interface" && symbol.name != "FUnknown")
    {
        module.push_str("    ");
        module.push_str(&rust_string_literal(&symbol.name));
        module.push_str(",\n");
    }
    module.push_str("];\n\n");
    module.push_str("pub const FUNKNOWN_METHODS: &[InterfaceMethod] = &[\n");
    for (slot, method) in interface_methods("FUnknown").iter().enumerate() {
        push_interface_method_record(&mut module, method, slot);
    }
    module.push_str("];\n\n");
    module.push_str("pub const FUNKNOWN_VTABLE_SLOTS: &[InterfaceVTableSlot] = &[\n");
    for (slot, method) in interface_methods("FUnknown").iter().enumerate() {
        push_interface_vtable_slot_record(&mut module, method, slot);
    }
    module.push_str("];\n\n");
    module.push_str("pub const FUNKNOWN_CALLBACK_TYPES: &[InterfaceCallbackType] = &[\n");
    for method in interface_methods("FUnknown") {
        push_interface_callback_type_record(&mut module, method);
    }
    module.push_str("];\n\n");
    module
        .push_str("pub const FUNKNOWN_VTABLE_FIELD_OFFSETS: &[InterfaceVTableFieldOffset] = &[\n");
    for method in interface_methods("FUnknown") {
        push_interface_vtable_field_offset_record(&mut module, method);
    }
    module.push_str("];\n\n");
    module.push_str("pub const FUNKNOWN_METHOD_COUNT: usize = ");
    module.push_str(&interface_methods("FUnknown").len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub const INTERFACE_IDS: &[InterfaceId] = &[\n");
    for spec in GENERATED_BINDINGS_INTERFACE_IDS {
        push_interface_id_record(&mut module, spec);
    }
    module.push_str("];\n\n");
    module.push_str("pub const QUERY_INTERFACE_ENTRIES: &[QueryInterfaceEntry] = &[\n");
    for spec in GENERATED_BINDINGS_INTERFACE_IDS {
        push_query_interface_entry_record(&mut module, spec);
    }
    module.push_str("];\n\n");
    module.push_str("pub fn interface_id_for_iid(iid: &TUID) -> Option<&'static InterfaceId> {\n");
    module.push_str("    for entry in INTERFACE_IDS {\n");
    module.push_str("        let candidate = iid_from_words(\n");
    module.push_str("            entry.uid_words[0],\n");
    module.push_str("            entry.uid_words[1],\n");
    module.push_str("            entry.uid_words[2],\n");
    module.push_str("            entry.uid_words[3],\n");
    module.push_str("        );\n");
    module.push_str("        if candidate.data == iid.data {\n");
    module.push_str("            return Some(entry);\n");
    module.push_str("        }\n");
    module.push_str("    }\n");
    module.push_str("    None\n");
    module.push_str("}\n\n");
    module.push_str(
        "pub fn query_interface_entry_by_interface(interface: &str) -> Option<&'static QueryInterfaceEntry> {\n",
    );
    module.push_str("    for entry in QUERY_INTERFACE_ENTRIES {\n");
    module.push_str("        if entry.interface == interface {\n");
    module.push_str("            return Some(entry);\n");
    module.push_str("        }\n");
    module.push_str("    }\n");
    module.push_str("    None\n");
    module.push_str("}\n\n");
    module.push_str(
        "pub fn query_interface_entry_for_iid(iid: &TUID) -> Option<&'static QueryInterfaceEntry> {\n",
    );
    module.push_str("    let interface_id = interface_id_for_iid(iid)?;\n");
    module.push_str("    query_interface_entry_by_interface(interface_id.interface)\n");
    module.push_str("}\n\n");
    module.push_str("pub const COM_OBJECTS: &[&str] = &[\n");
    for object in GENERATED_BINDINGS_COM_OBJECTS {
        module.push_str("    ");
        module.push_str(&rust_string_literal(object));
        module.push_str(",\n");
    }
    module.push_str("];\n\n");
    for object in GENERATED_BINDINGS_COM_OBJECTS {
        module.push_str("pub const ");
        module.push_str(&com_object_interfaces_const_name(object));
        module.push_str(": &[ComObjectInterface] = &[\n");
        for spec in GENERATED_BINDINGS_COM_OBJECT_INTERFACES
            .iter()
            .filter(|spec| spec.object == *object)
        {
            push_com_object_interface_record(&mut module, spec);
        }
        module.push_str("];\n\n");
        if let Some(identity) = com_object_identity_spec(object) {
            module.push_str("pub const ");
            module.push_str(&com_object_identity_plan_const_name(object));
            module.push_str(": ComObjectIdentityPlan = ");
            push_com_object_identity_plan_record(&mut module, identity);
            module.push_str(";\n\n");
            module.push_str("pub const ");
            module.push_str(&com_object_query_interface_dispatch_const_name(object));
            module.push_str(": &[ComObjectQueryInterfaceDispatchEntry] = &[\n");
            push_com_object_query_interface_dispatch_entry_record(
                &mut module,
                object,
                "FUnknown",
                identity.root_interface,
            );
            for spec in GENERATED_BINDINGS_COM_OBJECT_INTERFACES
                .iter()
                .filter(|spec| spec.object == *object)
            {
                push_com_object_query_interface_dispatch_entry_record(
                    &mut module,
                    spec.object,
                    spec.interface,
                    identity.root_interface,
                );
            }
            module.push_str("];\n\n");
        }
    }
    module.push_str("pub const COM_OBJECT_INTERFACES: &[ComObjectInterface] = &[\n");
    for spec in GENERATED_BINDINGS_COM_OBJECT_INTERFACES {
        push_com_object_interface_record(&mut module, spec);
    }
    module.push_str("];\n\n");
    module.push_str("pub const COM_OBJECT_IDENTITY_PLANS: &[ComObjectIdentityPlan] = &[\n");
    for identity in GENERATED_BINDINGS_COM_OBJECT_IDENTITIES {
        module.push_str("    ");
        push_com_object_identity_plan_record(&mut module, identity);
        module.push_str(",\n");
    }
    module.push_str("];\n\n");
    module.push_str("pub const COM_OBJECT_QUERY_INTERFACE_DISPATCH_ENTRIES: &[ComObjectQueryInterfaceDispatchEntry] = &[\n");
    for identity in GENERATED_BINDINGS_COM_OBJECT_IDENTITIES {
        push_com_object_query_interface_dispatch_entry_record(
            &mut module,
            identity.object,
            "FUnknown",
            identity.root_interface,
        );
    }
    for spec in GENERATED_BINDINGS_COM_OBJECT_INTERFACES {
        if let Some(identity) = com_object_identity_spec(spec.object) {
            push_com_object_query_interface_dispatch_entry_record(
                &mut module,
                spec.object,
                spec.interface,
                identity.root_interface,
            );
        }
    }
    module.push_str("];\n\n");
    module.push_str("pub fn com_object_query_interface_dispatch_by_interface(\n");
    module.push_str("    object: &str,\n");
    module.push_str("    interface: &str,\n");
    module.push_str(") -> Option<&'static ComObjectQueryInterfaceDispatchEntry> {\n");
    module.push_str("    for entry in COM_OBJECT_QUERY_INTERFACE_DISPATCH_ENTRIES {\n");
    module.push_str("        if entry.object == object && entry.interface == interface {\n");
    module.push_str("            return Some(entry);\n");
    module.push_str("        }\n");
    module.push_str("    }\n");
    module.push_str("    None\n");
    module.push_str("}\n\n");
    module.push_str("pub fn com_object_query_interface_dispatch_for_iid(\n");
    module.push_str("    object: &str,\n");
    module.push_str("    iid: &TUID,\n");
    module.push_str(") -> Option<&'static ComObjectQueryInterfaceDispatchEntry> {\n");
    module.push_str("    let interface_id = interface_id_for_iid(iid)?;\n");
    module.push_str(
        "    com_object_query_interface_dispatch_by_interface(object, interface_id.interface)\n",
    );
    module.push_str("}\n\n");
    module.push_str("pub const FACTORY_EXPORT_PLAN: FactoryExportPlan = ");
    push_factory_export_plan_record(&mut module, &GENERATED_BINDINGS_FACTORY_EXPORT_PLAN);
    module.push_str(";\n\n");
    for spec in GENERATED_BINDINGS_FACTORY_CLASS_PLANS {
        module.push_str("pub const ");
        module.push_str(&factory_class_plan_const_name(spec.class_object));
        module.push_str(": FactoryClassPlan = ");
        push_factory_class_plan_record(&mut module, spec);
        module.push_str(";\n\n");
    }
    module.push_str("pub const FACTORY_CLASS_PLANS: &[FactoryClassPlan] = &[\n");
    for spec in GENERATED_BINDINGS_FACTORY_CLASS_PLANS {
        module.push_str("    ");
        push_factory_class_plan_record(&mut module, spec);
        module.push_str(",\n");
    }
    module.push_str("];\n\n");
    for spec in GENERATED_BINDINGS_MODULE_EXPORT_PLANS {
        module.push_str("pub const ");
        module.push_str(spec.const_name);
        module.push_str(": ModuleExportPlan = ");
        push_module_export_plan_record(&mut module, spec);
        module.push_str(";\n\n");
    }
    module.push_str("pub const MODULE_EXPORT_PLANS: &[ModuleExportPlan] = &[\n");
    for spec in GENERATED_BINDINGS_MODULE_EXPORT_PLANS {
        module.push_str("    ");
        push_module_export_plan_record(&mut module, spec);
        module.push_str(",\n");
    }
    module.push_str("];\n\n");
    for spec in GENERATED_BINDINGS_BINARY_EXPORT_SYMBOL_PLANS {
        module.push_str("pub const ");
        module.push_str(spec.const_name);
        module.push_str(": BinaryExportSymbolPlan = ");
        push_binary_export_symbol_plan_record(&mut module, spec);
        module.push_str(";\n\n");
    }
    module.push_str("pub const BINARY_EXPORT_SYMBOL_PLANS: &[BinaryExportSymbolPlan] = &[\n");
    for spec in GENERATED_BINDINGS_BINARY_EXPORT_SYMBOL_PLANS {
        module.push_str("    ");
        push_binary_export_symbol_plan_record(&mut module, spec);
        module.push_str(",\n");
    }
    module.push_str("];\n\n");
    module.push_str(
        "pub const BINARY_EXPORT_INSPECTION_TOOL_PLANS: &[BinaryExportInspectionToolPlan] = &[\n",
    );
    for tool in BINARY_EXPORT_INSPECTION_TOOL_PLANS {
        push_binary_export_inspection_tool_plan_record(&mut module, tool);
    }
    module.push_str("];\n\n");
    module.push_str("pub fn binary_export_inspection_tools(\n");
    module.push_str("    platform: &str,\n");
    module.push_str(") -> &'static [BinaryExportInspectionToolPlan] {\n");
    module.push_str("    let mut start = None;\n");
    module.push_str("    let mut end = 0;\n");
    module.push_str("    let mut index = 0;\n");
    module.push_str("    while index < BINARY_EXPORT_INSPECTION_TOOL_PLANS.len() {\n");
    module.push_str("        let tool = &BINARY_EXPORT_INSPECTION_TOOL_PLANS[index];\n");
    module.push_str("        if tool.platform == platform {\n");
    module.push_str("            if start.is_none() {\n");
    module.push_str("                start = Some(index);\n");
    module.push_str("            }\n");
    module.push_str("            end = index + 1;\n");
    module.push_str("        } else if start.is_some() {\n");
    module.push_str("            break;\n");
    module.push_str("        }\n");
    module.push_str("        index += 1;\n");
    module.push_str("    }\n");
    module.push_str("    match start {\n");
    module.push_str("        Some(start) => &BINARY_EXPORT_INSPECTION_TOOL_PLANS[start..end],\n");
    module.push_str("        None => &[],\n");
    module.push_str("    }\n");
    module.push_str("}\n\n");
    module.push_str("pub fn binary_export_symbol_plan_by_platform_and_symbol(\n");
    module.push_str("    platform: &str,\n");
    module.push_str("    tool_symbol: &str,\n");
    module.push_str(") -> Option<&'static BinaryExportSymbolPlan> {\n");
    module.push_str("    for plan in BINARY_EXPORT_SYMBOL_PLANS {\n");
    module.push_str("        if plan.platform == platform && plan.tool_symbol == tool_symbol {\n");
    module.push_str("            return Some(plan);\n");
    module.push_str("        }\n");
    module.push_str("    }\n");
    module.push_str("    None\n");
    module.push_str("}\n\n");
    module.push_str("pub fn required_binary_export_symbol_count(platform: &str) -> usize {\n");
    module.push_str("    BINARY_EXPORT_SYMBOL_PLANS\n");
    module.push_str("        .iter()\n");
    module.push_str("        .filter(|plan| plan.platform == platform && plan.required)\n");
    module.push_str("        .count()\n");
    module.push_str("}\n\n");
    module.push_str("pub fn first_missing_binary_export_symbol(\n");
    module.push_str("    platform: &str,\n");
    module.push_str("    found_symbols: &[&str],\n");
    module.push_str(") -> Option<&'static str> {\n");
    module.push_str("    for plan in BINARY_EXPORT_SYMBOL_PLANS {\n");
    module.push_str("        if plan.platform == platform\n");
    module.push_str("            && plan.required\n");
    module
        .push_str("            && !found_symbols.iter().any(|found| *found == plan.tool_symbol)\n");
    module.push_str("        {\n");
    module.push_str("            return Some(plan.tool_symbol);\n");
    module.push_str("        }\n");
    module.push_str("    }\n");
    module.push_str("    None\n");
    module.push_str("}\n\n");
    module.push_str("pub fn binary_export_required_symbols_present(\n");
    module.push_str("    platform: &str,\n");
    module.push_str("    found_symbols: &[&str],\n");
    module.push_str(") -> bool {\n");
    module.push_str("    required_binary_export_symbol_count(platform) > 0\n");
    module.push_str(
        "        && first_missing_binary_export_symbol(platform, found_symbols).is_none()\n",
    );
    module.push_str("}\n\n");
    module.push_str("pub const INTERFACE_METHODS: &[InterfaceMethod] = &[\n");
    for method in GENERATED_BINDINGS_INTERFACE_METHODS {
        push_interface_method_record(&mut module, method, interface_method_slot(method));
    }
    module.push_str("];\n\n");
    module.push_str("pub const INTERFACE_VTABLE_SLOTS: &[InterfaceVTableSlot] = &[\n");
    for method in GENERATED_BINDINGS_INTERFACE_METHODS {
        push_interface_vtable_slot_record(&mut module, method, interface_method_slot(method));
    }
    module.push_str("];\n\n");
    module.push_str("pub fn interface_vtable_slot_by_interface_and_method(\n");
    module.push_str("    interface: &str,\n");
    module.push_str("    method: &str,\n");
    module.push_str(") -> Option<&'static InterfaceVTableSlot> {\n");
    module.push_str("    for slot in INTERFACE_VTABLE_SLOTS {\n");
    module.push_str("        if slot.interface == interface && slot.method == method {\n");
    module.push_str("            return Some(slot);\n");
    module.push_str("        }\n");
    module.push_str("    }\n");
    module.push_str("    None\n");
    module.push_str("}\n\n");
    module.push_str("pub fn interface_vtable_slot_by_interface_and_global_slot(\n");
    module.push_str("    interface: &str,\n");
    module.push_str("    global_slot: usize,\n");
    module.push_str(") -> Option<&'static InterfaceVTableSlot> {\n");
    module.push_str("    for slot in INTERFACE_VTABLE_SLOTS {\n");
    module
        .push_str("        if slot.interface == interface && slot.global_slot == global_slot {\n");
    module.push_str("            return Some(slot);\n");
    module.push_str("        }\n");
    module.push_str("    }\n");
    module.push_str("    None\n");
    module.push_str("}\n\n");
    module.push_str("pub const INTERFACE_CALLBACK_TYPES: &[InterfaceCallbackType] = &[\n");
    for method in GENERATED_BINDINGS_INTERFACE_METHODS {
        push_interface_callback_type_record(&mut module, method);
    }
    module.push_str("];\n\n");
    module
        .push_str("pub const INTERFACE_VTABLE_FIELD_OFFSETS: &[InterfaceVTableFieldOffset] = &[\n");
    for method in GENERATED_BINDINGS_INTERFACE_METHODS {
        push_interface_vtable_field_offset_record(&mut module, method);
    }
    module.push_str("];\n\n");
    module.push_str("pub fn interface_vtable_field_offset_by_interface_and_field(\n");
    module.push_str("    interface: &str,\n");
    module.push_str("    field: &str,\n");
    module.push_str(") -> Option<&'static InterfaceVTableFieldOffset> {\n");
    module.push_str("    for offset in INTERFACE_VTABLE_FIELD_OFFSETS {\n");
    module.push_str("        if offset.interface == interface && offset.field == field {\n");
    module.push_str("            return Some(offset);\n");
    module.push_str("        }\n");
    module.push_str("    }\n");
    module.push_str("    None\n");
    module.push_str("}\n\n");
    module.push_str("pub const HEADER_INPUTS: &[HeaderInput] = &[\n");
    for header in &plan.header_manifest.headers {
        module.push_str("    HeaderInput { path: ");
        module.push_str(&rust_string_literal(&header.path));
        module.push_str(", size: ");
        module.push_str(&header.size.to_string());
        module.push_str(", sha256: ");
        module.push_str(&rust_string_literal(&header.sha256));
        module.push_str(" },\n");
    }
    module.push_str("];\n\n");
    module.push_str("pub const MISSING_HEADERS: &[&str] = &[\n");
    for header in &plan.header_manifest.missing_headers {
        module.push_str("    ");
        module.push_str(&rust_string_literal(header));
        module.push_str(",\n");
    }
    module.push_str("];\n\n");
    module.push_str("pub const BINDING_SURFACE_SYMBOLS: &[BindingSymbol] = &[\n");
    for symbol in &surface.symbols {
        module.push_str("    BindingSymbol { name: ");
        module.push_str(&rust_string_literal(&symbol.name));
        module.push_str(", kind: ");
        module.push_str(&rust_string_literal(&symbol.kind));
        module.push_str(", header: ");
        module.push_str(&rust_string_literal(&symbol.header));
        module.push_str(", purpose: ");
        module.push_str(&rust_string_literal(&symbol.purpose));
        module.push_str(", symbol_present: ");
        module.push_str(if symbol.symbol_present {
            "true"
        } else {
            "false"
        });
        module.push_str(" },\n");
    }
    module.push_str("];\n\n");
    module.push_str("pub const fn interface_skeleton_is_generated() -> bool {\n");
    module.push_str("    INTERFACE_SKELETON_GENERATED\n");
    module.push_str("}\n\n");
    module.push_str("pub const fn full_com_bindings_are_generated() -> bool {\n");
    module.push_str("    FULL_COM_BINDINGS_GENERATED\n");
    module.push_str("}\n");
    module
}

pub(crate) fn push_interface_method_record(
    module: &mut String,
    method: &BindingInterfaceMethodSpec,
    slot: usize,
) {
    let signature = interface_method_signature_intent(method);
    module.push_str("    InterfaceMethod { slot: ");
    module.push_str(&slot.to_string());
    module.push_str(", interface: ");
    module.push_str(&rust_string_literal(method.interface));
    module.push_str(", name: ");
    module.push_str(&rust_string_literal(method.name));
    module.push_str(", purpose: ");
    module.push_str(&rust_string_literal(method.purpose));
    module.push_str(", realtime: ");
    module.push_str(if method.realtime { "true" } else { "false" });
    module.push_str(", signature: ");
    module.push_str(&rust_string_literal(&signature));
    module.push_str(" },\n");
}

pub(crate) fn push_interface_vtable_slot_record(
    module: &mut String,
    method: &BindingInterfaceMethodSpec,
    slot: usize,
) {
    let signature = interface_method_signature_intent(method);
    module.push_str("    InterfaceVTableSlot { local_slot: ");
    module.push_str(&slot.to_string());
    module.push_str(", global_slot: ");
    module.push_str(&interface_method_global_slot(method, slot).to_string());
    module.push_str(", interface: ");
    module.push_str(&rust_string_literal(method.interface));
    module.push_str(", method: ");
    module.push_str(&rust_string_literal(method.name));
    module.push_str(", field: ");
    module.push_str(&rust_string_literal(method.name));
    module.push_str(", callback_type: ");
    module.push_str(&rust_string_literal(&interface_method_callback_type_name(
        method,
    )));
    module.push_str(", signature: ");
    module.push_str(&rust_string_literal(&signature));
    module.push_str(" },\n");
}

pub(crate) fn push_interface_vtable_field(
    module: &mut String,
    method: &BindingInterfaceMethodSpec,
) {
    module.push_str("    pub ");
    module.push_str(method.name);
    module.push_str(": ");
    module.push_str(&interface_method_callback_type_name(method));
    module.push_str(",\n");
}

pub(crate) fn push_interface_callback_type_alias(
    module: &mut String,
    method: &BindingInterfaceMethodSpec,
) {
    module.push_str("pub type ");
    module.push_str(&interface_method_callback_type_name(method));
    module.push_str(" = ");
    module.push_str(&interface_method_signature_intent(method));
    module.push_str(";\n");
}

pub(crate) fn push_interface_callback_type_record(
    module: &mut String,
    method: &BindingInterfaceMethodSpec,
) {
    let signature = interface_method_signature_intent(method);
    module.push_str("    InterfaceCallbackType { interface: ");
    module.push_str(&rust_string_literal(method.interface));
    module.push_str(", method: ");
    module.push_str(&rust_string_literal(method.name));
    module.push_str(", callback_type: ");
    module.push_str(&rust_string_literal(&interface_method_callback_type_name(
        method,
    )));
    module.push_str(", signature: ");
    module.push_str(&rust_string_literal(&signature));
    module.push_str(" },\n");
}

pub(crate) fn push_interface_vtable_field_offset_record(
    module: &mut String,
    method: &BindingInterfaceMethodSpec,
) {
    let callback_type = interface_method_callback_type_name(method);
    let vtable_type = format!("{}VTable", method.interface);
    module.push_str("    InterfaceVTableFieldOffset { interface: ");
    module.push_str(&rust_string_literal(method.interface));
    module.push_str(", field: ");
    module.push_str(&rust_string_literal(method.name));
    module.push_str(", callback_type: ");
    module.push_str(&rust_string_literal(&callback_type));
    module.push_str(", offset: std::mem::offset_of!(");
    module.push_str(&vtable_type);
    module.push_str(", ");
    module.push_str(method.name);
    module.push_str(") },\n");
}

pub(crate) fn push_interface_iid_const(module: &mut String, spec: &BindingInterfaceIdSpec) {
    module.push_str("pub const ");
    module.push_str(&interface_iid_const_name(spec.interface));
    module.push_str(": TUID = iid_from_words(");
    for (index, word) in spec.uid_words.iter().enumerate() {
        if index > 0 {
            module.push_str(", ");
        }
        module.push_str(&format!("0x{word:08X}"));
    }
    module.push_str(");\n");
}

pub(crate) fn push_interface_id_record(module: &mut String, spec: &BindingInterfaceIdSpec) {
    module.push_str("    InterfaceId { interface: ");
    module.push_str(&rust_string_literal(spec.interface));
    module.push_str(", iid_const: ");
    module.push_str(&rust_string_literal(&interface_iid_const_name(
        spec.interface,
    )));
    module.push_str(", uid_words: [");
    for (index, word) in spec.uid_words.iter().enumerate() {
        if index > 0 {
            module.push_str(", ");
        }
        module.push_str(&format!("0x{word:08X}"));
    }
    module.push_str("], source: ");
    module.push_str(&rust_string_literal(spec.source));
    module.push_str(" },\n");
}

pub(crate) fn push_query_interface_entry_record(
    module: &mut String,
    spec: &BindingInterfaceIdSpec,
) {
    module.push_str("    QueryInterfaceEntry { interface: ");
    module.push_str(&rust_string_literal(spec.interface));
    module.push_str(", iid_const: ");
    module.push_str(&rust_string_literal(&interface_iid_const_name(
        spec.interface,
    )));
    module.push_str(", inherits_funknown: ");
    module.push_str(if spec.interface == "FUnknown" {
        "false"
    } else {
        "true"
    });
    module.push_str(", implementation: \"planned-dispatch-entry-no-callable-glue\" },\n");
}

pub(crate) fn push_com_object_interface_record(
    module: &mut String,
    spec: &BindingComObjectInterfaceSpec,
) {
    module.push_str("    ComObjectInterface { object: ");
    module.push_str(&rust_string_literal(spec.object));
    module.push_str(", interface: ");
    module.push_str(&rust_string_literal(spec.interface));
    module.push_str(", iid_const: ");
    module.push_str(&rust_string_literal(&interface_iid_const_name(
        spec.interface,
    )));
    module.push_str(", exposure: ");
    module.push_str(&rust_string_literal(spec.exposure));
    module.push_str(", source: ");
    module.push_str(&rust_string_literal(spec.source));
    module.push_str(", required: ");
    module.push_str(if spec.required { "true" } else { "false" });
    module.push_str(" },\n");
}

pub(crate) fn push_com_object_identity_plan_record(
    module: &mut String,
    spec: &BindingComObjectIdentitySpec,
) {
    module.push_str("ComObjectIdentityPlan { object: ");
    module.push_str(&rust_string_literal(spec.object));
    module.push_str(", root_interface: ");
    module.push_str(&rust_string_literal(spec.root_interface));
    module.push_str(", root_iid_const: ");
    module.push_str(&rust_string_literal(&interface_iid_const_name(
        spec.root_interface,
    )));
    module.push_str(", funknown_identity: ");
    module.push_str(&rust_string_literal(spec.funknown_identity));
    module.push_str(", refcount_policy: ");
    module.push_str(&rust_string_literal(spec.refcount_policy));
    module.push_str(", unknown_iid_result: ");
    module.push_str(&rust_string_literal(spec.unknown_iid_result));
    module.push_str(", null_object_pointer_result: ");
    module.push_str(&rust_string_literal(spec.null_object_pointer_result));
    module.push_str(", source: ");
    module.push_str(&rust_string_literal(spec.source));
    module.push_str(" }");
}

pub(crate) fn push_com_object_query_interface_dispatch_entry_record(
    module: &mut String,
    object: &str,
    interface: &str,
    root_interface: &str,
) {
    module.push_str("    ComObjectQueryInterfaceDispatchEntry { object: ");
    module.push_str(&rust_string_literal(object));
    module.push_str(", interface: ");
    module.push_str(&rust_string_literal(interface));
    module.push_str(", iid_const: ");
    module.push_str(&rust_string_literal(&interface_iid_const_name(interface)));
    module.push_str(", root_interface: ");
    module.push_str(&rust_string_literal(root_interface));
    module.push_str(", returns_same_identity: true");
    module.push_str(", success_result: \"kResultOk\"");
    module.push_str(", add_ref_on_success: true");
    module.push_str(
        ", implementation: \"planned-object-query-interface-dispatch-no-callable-glue\" },\n",
    );
}

pub(crate) fn push_factory_export_plan_record(
    module: &mut String,
    spec: &BindingFactoryExportPlanSpec,
) {
    module.push_str("FactoryExportPlan { factory_object: ");
    module.push_str(&rust_string_literal(spec.factory_object));
    module.push_str(", factory_interface: ");
    module.push_str(&rust_string_literal(spec.factory_interface));
    module.push_str(", factory_iid_const: ");
    module.push_str(&rust_string_literal(&interface_iid_const_name(
        spec.factory_interface,
    )));
    module.push_str(", class_count: ");
    module.push_str(&spec.class_count.to_string());
    module.push_str(", count_classes_result: ");
    module.push_str(&rust_string_literal(spec.count_classes_result));
    module.push_str(", get_factory_info_source: ");
    module.push_str(&rust_string_literal(spec.get_factory_info_source));
    module.push_str(", source: ");
    module.push_str(&rust_string_literal(spec.source));
    module.push_str(" }");
}

pub(crate) fn push_factory_class_plan_record(
    module: &mut String,
    spec: &BindingFactoryClassPlanSpec,
) {
    module.push_str("FactoryClassPlan { class_kind: ");
    module.push_str(&rust_string_literal(spec.class_kind));
    module.push_str(", class_index: ");
    module.push_str(&spec.class_index.to_string());
    module.push_str(", class_object: ");
    module.push_str(&rust_string_literal(spec.class_object));
    module.push_str(", root_interface: ");
    module.push_str(&rust_string_literal(spec.root_interface));
    module.push_str(", root_iid_const: ");
    module.push_str(&rust_string_literal(&interface_iid_const_name(
        spec.root_interface,
    )));
    module.push_str(", category: ");
    module.push_str(&rust_string_literal(spec.category));
    module.push_str(", name_source: ");
    module.push_str(&rust_string_literal(spec.name_source));
    module.push_str(", cid_source: ");
    module.push_str(&rust_string_literal(spec.cid_source));
    module.push_str(", cid_policy: ");
    module.push_str(&rust_string_literal(spec.cid_policy));
    module.push_str(", cardinality: ");
    module.push_str(&rust_string_literal(spec.cardinality));
    module.push_str(", get_class_info_result: ");
    module.push_str(&rust_string_literal(spec.get_class_info_result));
    module.push_str(", invalid_class_index_result: ");
    module.push_str(&rust_string_literal(spec.invalid_class_index_result));
    module.push_str(", create_instance_object: ");
    module.push_str(&rust_string_literal(spec.create_instance_object));
    module.push_str(", create_instance_root_interface: ");
    module.push_str(&rust_string_literal(spec.create_instance_root_interface));
    module.push_str(", create_instance_root_iid_const: ");
    module.push_str(&rust_string_literal(&interface_iid_const_name(
        spec.create_instance_root_interface,
    )));
    module.push_str(", unknown_cid_result: ");
    module.push_str(&rust_string_literal(spec.unknown_cid_result));
    module.push_str(", construction_failure_result: ");
    module.push_str(&rust_string_literal(spec.construction_failure_result));
    module.push_str(", requested_iid_dispatch: ");
    module.push_str(&rust_string_literal(spec.requested_iid_dispatch));
    module.push_str(", source: ");
    module.push_str(&rust_string_literal(spec.source));
    module.push_str(" }");
}

pub(crate) fn push_module_export_plan_record(
    module: &mut String,
    spec: &BindingModuleExportPlanSpec,
) {
    module.push_str("ModuleExportPlan { symbol: ");
    module.push_str(&rust_string_literal(spec.symbol));
    module.push_str(", platforms: ");
    module.push_str(&rust_string_literal(spec.platforms));
    module.push_str(", signature: ");
    module.push_str(&rust_string_literal(spec.signature));
    module.push_str(", purpose: ");
    module.push_str(&rust_string_literal(spec.purpose));
    module.push_str(", implementation: ");
    module.push_str(&rust_string_literal(spec.implementation));
    module.push_str(", return_policy: ");
    module.push_str(&rust_string_literal(spec.return_policy));
    module.push_str(", generated_callable: ");
    module.push_str(if spec.generated_callable {
        "true"
    } else {
        "false"
    });
    module.push_str(", source: ");
    module.push_str(&rust_string_literal(spec.source));
    module.push_str(" }");
}

pub(crate) fn push_binary_export_symbol_plan_record(
    module: &mut String,
    spec: &BindingBinaryExportSymbolPlanSpec,
) {
    module.push_str("BinaryExportSymbolPlan { platform: ");
    module.push_str(&rust_string_literal(spec.platform));
    module.push_str(", binary_format: ");
    module.push_str(&rust_string_literal(spec.binary_format));
    module.push_str(", symbol: ");
    module.push_str(&rust_string_literal(spec.symbol));
    module.push_str(", tool_symbol: ");
    module.push_str(&rust_string_literal(spec.tool_symbol));
    module.push_str(", inspection_tool: ");
    module.push_str(&rust_string_literal(spec.inspection_tool));
    module.push_str(", required: ");
    module.push_str(if spec.required { "true" } else { "false" });
    module.push_str(", verified_by_generated_bindings: ");
    module.push_str(if spec.verified_by_generated_bindings {
        "true"
    } else {
        "false"
    });
    module.push_str(", source: ");
    module.push_str(&rust_string_literal(spec.source));
    module.push_str(" }");
}

pub(crate) fn push_binary_export_inspection_tool_plan_record(
    module: &mut String,
    tool: &BinaryExportInspectionToolPlan,
) {
    module.push_str("    BinaryExportInspectionToolPlan { platform: ");
    module.push_str(&rust_string_literal(tool.platform));
    module.push_str(", program: ");
    module.push_str(&rust_string_literal(tool.program));
    module.push_str(", args: &[");
    for (index, arg) in tool.args.iter().enumerate() {
        if index > 0 {
            module.push_str(", ");
        }
        module.push_str(&rust_string_literal(arg));
    }
    module.push_str("] },\n");
}

pub(crate) fn interface_method_slot(method: &BindingInterfaceMethodSpec) -> usize {
    interface_methods(method.interface)
        .iter()
        .position(|candidate| candidate.name == method.name)
        .unwrap_or(0)
}

pub(crate) fn interface_method_global_slot(
    method: &BindingInterfaceMethodSpec,
    local_slot: usize,
) -> usize {
    if method.interface == "FUnknown" {
        local_slot
    } else {
        3 + local_slot
    }
}

pub(crate) fn interface_method_callback_type_name(method: &BindingInterfaceMethodSpec) -> String {
    let mut callback = String::from(method.interface);
    let mut capitalize_next = true;
    for character in method.name.chars() {
        if !character.is_ascii_alphanumeric() {
            capitalize_next = true;
            continue;
        }
        if capitalize_next {
            callback.push(character.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            callback.push(character);
        }
    }
    callback
}

pub(crate) fn interface_method_signature_intent(method: &BindingInterfaceMethodSpec) -> String {
    let signature = match (method.interface, method.name) {
        ("FUnknown", "queryInterface") => {
            "unsafe extern \"system\" fn(this: *mut FUnknown, iid: *const TUID, obj: *mut *mut std::ffi::c_void) -> TResult"
        }
        ("FUnknown", "addRef") => "unsafe extern \"system\" fn(this: *mut FUnknown) -> uint32",
        ("FUnknown", "release") => "unsafe extern \"system\" fn(this: *mut FUnknown) -> uint32",
        ("IPluginFactory", "countClasses") => {
            "unsafe extern \"system\" fn(this: *mut IPluginFactory) -> int32"
        }
        ("IPluginFactory", "getClassInfo") => {
            "unsafe extern \"system\" fn(this: *mut IPluginFactory, index: int32, info: *mut PClassInfo) -> TResult"
        }
        ("IPluginFactory", "createInstance") => {
            "unsafe extern \"system\" fn(this: *mut IPluginFactory, cid: FIDString, iid: FIDString, obj: *mut *mut std::ffi::c_void) -> TResult"
        }
        ("IPluginBase", "initialize") => {
            "unsafe extern \"system\" fn(this: *mut IPluginBase, context: *mut FUnknown) -> TResult"
        }
        ("IPluginBase", "terminate") => {
            "unsafe extern \"system\" fn(this: *mut IPluginBase) -> TResult"
        }
        ("IConnectionPoint", "connect") => {
            "unsafe extern \"system\" fn(this: *mut IConnectionPoint, other: *mut IConnectionPoint) -> TResult"
        }
        ("IConnectionPoint", "disconnect") => {
            "unsafe extern \"system\" fn(this: *mut IConnectionPoint, other: *mut IConnectionPoint) -> TResult"
        }
        ("IConnectionPoint", "notify") => {
            "unsafe extern \"system\" fn(this: *mut IConnectionPoint, message: *mut IMessage) -> TResult"
        }
        ("IBStream", "read") => {
            "unsafe extern \"system\" fn(this: *mut IBStream, buffer: *mut std::ffi::c_void, num_bytes: int32, num_bytes_read: *mut int32) -> TResult"
        }
        ("IBStream", "write") => {
            "unsafe extern \"system\" fn(this: *mut IBStream, buffer: *mut std::ffi::c_void, num_bytes: int32, num_bytes_written: *mut int32) -> TResult"
        }
        ("IBStream", "seek") => {
            "unsafe extern \"system\" fn(this: *mut IBStream, pos: int64, mode: int32, result: *mut int64) -> TResult"
        }
        ("IBStream", "tell") => {
            "unsafe extern \"system\" fn(this: *mut IBStream, pos: *mut int64) -> TResult"
        }
        ("IPlugView", "isPlatformTypeSupported") => {
            "unsafe extern \"system\" fn(this: *mut IPlugView, type_: FIDString) -> TResult"
        }
        ("IPlugView", "attached") => {
            "unsafe extern \"system\" fn(this: *mut IPlugView, parent: *mut std::ffi::c_void, type_: FIDString) -> TResult"
        }
        ("IPlugView", "removed") => "unsafe extern \"system\" fn(this: *mut IPlugView) -> TResult",
        ("IPlugView", "onWheel") => {
            "unsafe extern \"system\" fn(this: *mut IPlugView, distance: f32) -> TResult"
        }
        ("IPlugView", "onKeyDown") => {
            "unsafe extern \"system\" fn(this: *mut IPlugView, key: char16, key_code: int16, modifiers: int16) -> TResult"
        }
        ("IPlugView", "onKeyUp") => {
            "unsafe extern \"system\" fn(this: *mut IPlugView, key: char16, key_code: int16, modifiers: int16) -> TResult"
        }
        ("IPlugView", "getSize") => {
            "unsafe extern \"system\" fn(this: *mut IPlugView, size: *mut ViewRect) -> TResult"
        }
        ("IPlugView", "onSize") => {
            "unsafe extern \"system\" fn(this: *mut IPlugView, new_size: *mut ViewRect) -> TResult"
        }
        ("IPlugView", "onFocus") => {
            "unsafe extern \"system\" fn(this: *mut IPlugView, state: TBool) -> TResult"
        }
        ("IPlugView", "setFrame") => {
            "unsafe extern \"system\" fn(this: *mut IPlugView, frame: *mut IPlugFrame) -> TResult"
        }
        ("IPlugView", "canResize") => {
            "unsafe extern \"system\" fn(this: *mut IPlugView) -> TResult"
        }
        ("IPlugView", "checkSizeConstraint") => {
            "unsafe extern \"system\" fn(this: *mut IPlugView, rect: *mut ViewRect) -> TResult"
        }
        ("IPlugFrame", "resizeView") => {
            "unsafe extern \"system\" fn(this: *mut IPlugFrame, view: *mut IPlugView, new_size: *mut ViewRect) -> TResult"
        }
        ("IComponent", "getControllerClassId") => {
            "unsafe extern \"system\" fn(this: *mut IComponent, class_id: *mut TUID) -> TResult"
        }
        ("IComponent", "setIoMode") => {
            "unsafe extern \"system\" fn(this: *mut IComponent, mode: IoMode) -> TResult"
        }
        ("IComponent", "getBusCount") => {
            "unsafe extern \"system\" fn(this: *mut IComponent, type_: MediaType, dir: BusDirection) -> int32"
        }
        ("IComponent", "getBusInfo") => {
            "unsafe extern \"system\" fn(this: *mut IComponent, type_: MediaType, dir: BusDirection, index: int32, bus: *mut BusInfo) -> TResult"
        }
        ("IComponent", "getRoutingInfo") => {
            "unsafe extern \"system\" fn(this: *mut IComponent, in_info: *mut RoutingInfo, out_info: *mut RoutingInfo) -> TResult"
        }
        ("IComponent", "activateBus") => {
            "unsafe extern \"system\" fn(this: *mut IComponent, type_: MediaType, dir: BusDirection, index: int32, state: TBool) -> TResult"
        }
        ("IComponent", "setActive") => {
            "unsafe extern \"system\" fn(this: *mut IComponent, state: TBool) -> TResult"
        }
        ("IComponent", "setState") => {
            "unsafe extern \"system\" fn(this: *mut IComponent, state: *mut IBStream) -> TResult"
        }
        ("IComponent", "getState") => {
            "unsafe extern \"system\" fn(this: *mut IComponent, state: *mut IBStream) -> TResult"
        }
        ("IAudioProcessor", "setBusArrangements") => {
            "unsafe extern \"system\" fn(this: *mut IAudioProcessor, inputs: *mut SpeakerArrangement, num_ins: int32, outputs: *mut SpeakerArrangement, num_outs: int32) -> TResult"
        }
        ("IAudioProcessor", "getBusArrangement") => {
            "unsafe extern \"system\" fn(this: *mut IAudioProcessor, dir: BusDirection, index: int32, arr: *mut SpeakerArrangement) -> TResult"
        }
        ("IAudioProcessor", "canProcessSampleSize") => {
            "unsafe extern \"system\" fn(this: *mut IAudioProcessor, symbolic_sample_size: int32) -> TResult"
        }
        ("IAudioProcessor", "getLatencySamples") => {
            "unsafe extern \"system\" fn(this: *mut IAudioProcessor) -> uint32"
        }
        ("IAudioProcessor", "setupProcessing") => {
            "unsafe extern \"system\" fn(this: *mut IAudioProcessor, setup: *mut ProcessSetup) -> TResult"
        }
        ("IAudioProcessor", "setProcessing") => {
            "unsafe extern \"system\" fn(this: *mut IAudioProcessor, state: TBool) -> TResult"
        }
        ("IAudioProcessor", "process") => {
            "unsafe extern \"system\" fn(this: *mut IAudioProcessor, data: *mut ProcessData) -> TResult"
        }
        ("IAudioProcessor", "getTailSamples") => {
            "unsafe extern \"system\" fn(this: *mut IAudioProcessor) -> uint32"
        }
        ("IProcessContextRequirements", "getProcessContextRequirements") => {
            "unsafe extern \"system\" fn(this: *mut IProcessContextRequirements) -> uint32"
        }
        ("IEditController", "setComponentState") => {
            "unsafe extern \"system\" fn(this: *mut IEditController, state: *mut IBStream) -> TResult"
        }
        ("IEditController", "setState") => {
            "unsafe extern \"system\" fn(this: *mut IEditController, state: *mut IBStream) -> TResult"
        }
        ("IEditController", "getState") => {
            "unsafe extern \"system\" fn(this: *mut IEditController, state: *mut IBStream) -> TResult"
        }
        ("IEditController", "getParameterCount") => {
            "unsafe extern \"system\" fn(this: *mut IEditController) -> int32"
        }
        ("IEditController", "getParameterInfo") => {
            "unsafe extern \"system\" fn(this: *mut IEditController, param_index: int32, info: *mut ParameterInfo) -> TResult"
        }
        ("IEditController", "getParamStringByValue") => {
            "unsafe extern \"system\" fn(this: *mut IEditController, id: ParamID, value_normalized: ParamValue, string: String128) -> TResult"
        }
        ("IEditController", "getParamValueByString") => {
            "unsafe extern \"system\" fn(this: *mut IEditController, id: ParamID, string: TCharConstPtr, value_normalized: *mut ParamValue) -> TResult"
        }
        ("IEditController", "normalizedParamToPlain") => {
            "unsafe extern \"system\" fn(this: *mut IEditController, id: ParamID, value_normalized: ParamValue) -> ParamValue"
        }
        ("IEditController", "plainParamToNormalized") => {
            "unsafe extern \"system\" fn(this: *mut IEditController, id: ParamID, plain_value: ParamValue) -> ParamValue"
        }
        ("IEditController", "getParamNormalized") => {
            "unsafe extern \"system\" fn(this: *mut IEditController, id: ParamID) -> ParamValue"
        }
        ("IEditController", "setParamNormalized") => {
            "unsafe extern \"system\" fn(this: *mut IEditController, id: ParamID, value: ParamValue) -> TResult"
        }
        ("IEditController", "setComponentHandler") => {
            "unsafe extern \"system\" fn(this: *mut IEditController, handler: *mut IComponentHandler) -> TResult"
        }
        ("IEditController", "createView") => {
            "unsafe extern \"system\" fn(this: *mut IEditController, name: FIDString) -> *mut IPlugView"
        }
        ("IComponentHandler", "beginEdit") => {
            "unsafe extern \"system\" fn(this: *mut IComponentHandler, id: ParamID) -> TResult"
        }
        ("IComponentHandler", "performEdit") => {
            "unsafe extern \"system\" fn(this: *mut IComponentHandler, id: ParamID, value_normalized: ParamValue) -> TResult"
        }
        ("IComponentHandler", "endEdit") => {
            "unsafe extern \"system\" fn(this: *mut IComponentHandler, id: ParamID) -> TResult"
        }
        ("IComponentHandler", "restartComponent") => {
            "unsafe extern \"system\" fn(this: *mut IComponentHandler, flags: int32) -> TResult"
        }
        ("IMidiMapping", "getMidiControllerAssignment") => {
            "unsafe extern \"system\" fn(this: *mut IMidiMapping, bus_index: int32, channel: int16, midi_controller_number: CtrlNumber, id: *mut ParamID) -> TResult"
        }
        ("INoteExpressionController", "getNoteExpressionCount") => {
            "unsafe extern \"system\" fn(this: *mut INoteExpressionController, bus_index: int32, channel: int16) -> int32"
        }
        ("INoteExpressionController", "getNoteExpressionInfo") => {
            "unsafe extern \"system\" fn(this: *mut INoteExpressionController, bus_index: int32, channel: int16, note_expression_index: int32, info: *mut NoteExpressionTypeInfo) -> TResult"
        }
        ("INoteExpressionController", "getNoteExpressionStringByValue") => {
            "unsafe extern \"system\" fn(this: *mut INoteExpressionController, bus_index: int32, channel: int16, id: NoteExpressionTypeID, value: NoteExpressionValue, string: String128) -> TResult"
        }
        ("INoteExpressionController", "getNoteExpressionValueByString") => {
            "unsafe extern \"system\" fn(this: *mut INoteExpressionController, bus_index: int32, channel: int16, id: NoteExpressionTypeID, string: TCharConstPtr, value: *mut NoteExpressionValue) -> TResult"
        }
        ("INoteExpressionPhysicalUIMapping", "getPhysicalUIMapping") => {
            "unsafe extern \"system\" fn(this: *mut INoteExpressionPhysicalUIMapping, bus_index: int32, channel: int16, list: *mut PhysicalUIMapList) -> TResult"
        }
        ("IParameterChanges", "getParameterCount") => {
            "unsafe extern \"system\" fn(this: *mut IParameterChanges) -> int32"
        }
        ("IParameterChanges", "getParameterData") => {
            "unsafe extern \"system\" fn(this: *mut IParameterChanges, index: int32) -> *mut IParamValueQueue"
        }
        ("IParamValueQueue", "getParameterId") => {
            "unsafe extern \"system\" fn(this: *mut IParamValueQueue) -> ParamID"
        }
        ("IParamValueQueue", "getPointCount") => {
            "unsafe extern \"system\" fn(this: *mut IParamValueQueue) -> int32"
        }
        ("IParamValueQueue", "getPoint") => {
            "unsafe extern \"system\" fn(this: *mut IParamValueQueue, index: int32, sample_offset: *mut int32, value: *mut ParamValue) -> TResult"
        }
        ("IParamValueQueue", "addPoint") => {
            "unsafe extern \"system\" fn(this: *mut IParamValueQueue, sample_offset: int32, value: ParamValue, index: *mut int32) -> TResult"
        }
        ("IEventList", "getEventCount") => {
            "unsafe extern \"system\" fn(this: *mut IEventList) -> int32"
        }
        ("IEventList", "getEvent") => {
            "unsafe extern \"system\" fn(this: *mut IEventList, index: int32, event: *mut Event) -> TResult"
        }
        ("IEventList", "addEvent") => {
            "unsafe extern \"system\" fn(this: *mut IEventList, event: *mut Event) -> TResult"
        }
        ("IMessage", "getMessageID") => {
            "unsafe extern \"system\" fn(this: *mut IMessage) -> FIDString"
        }
        ("IMessage", "setMessageID") => {
            "unsafe extern \"system\" fn(this: *mut IMessage, id: FIDString) -> ()"
        }
        ("IMessage", "getAttributes") => {
            "unsafe extern \"system\" fn(this: *mut IMessage) -> *mut IAttributeList"
        }
        ("IAttributeList", "setInt") => {
            "unsafe extern \"system\" fn(this: *mut IAttributeList, id: AttrID, value: int64) -> TResult"
        }
        ("IAttributeList", "getInt") => {
            "unsafe extern \"system\" fn(this: *mut IAttributeList, id: AttrID, value: *mut int64) -> TResult"
        }
        ("IAttributeList", "setFloat") => {
            "unsafe extern \"system\" fn(this: *mut IAttributeList, id: AttrID, value: f64) -> TResult"
        }
        ("IAttributeList", "getFloat") => {
            "unsafe extern \"system\" fn(this: *mut IAttributeList, id: AttrID, value: *mut f64) -> TResult"
        }
        ("IAttributeList", "setString") => {
            "unsafe extern \"system\" fn(this: *mut IAttributeList, id: AttrID, string: *const TChar) -> TResult"
        }
        ("IAttributeList", "getString") => {
            "unsafe extern \"system\" fn(this: *mut IAttributeList, id: AttrID, string: *mut TChar, size_in_bytes: uint32) -> TResult"
        }
        ("IAttributeList", "setBinary") => {
            "unsafe extern \"system\" fn(this: *mut IAttributeList, id: AttrID, data: *const std::ffi::c_void, size_in_bytes: uint32) -> TResult"
        }
        ("IAttributeList", "getBinary") => {
            "unsafe extern \"system\" fn(this: *mut IAttributeList, id: AttrID, data: *mut *const std::ffi::c_void, size_in_bytes: *mut uint32) -> TResult"
        }
        ("IUnitInfo", "getUnitCount") => {
            "unsafe extern \"system\" fn(this: *mut IUnitInfo) -> int32"
        }
        ("IUnitInfo", "getUnitInfo") => {
            "unsafe extern \"system\" fn(this: *mut IUnitInfo, unit_index: int32, info: *mut UnitInfo) -> TResult"
        }
        ("IUnitInfo", "getProgramListCount") => {
            "unsafe extern \"system\" fn(this: *mut IUnitInfo) -> int32"
        }
        ("IUnitInfo", "getProgramListInfo") => {
            "unsafe extern \"system\" fn(this: *mut IUnitInfo, list_index: int32, info: *mut ProgramListInfo) -> TResult"
        }
        ("IUnitInfo", "getProgramName") => {
            "unsafe extern \"system\" fn(this: *mut IUnitInfo, list_id: ProgramListID, program_index: int32, name: String128) -> TResult"
        }
        ("IUnitInfo", "getProgramInfo") => {
            "unsafe extern \"system\" fn(this: *mut IUnitInfo, list_id: ProgramListID, program_index: int32, attribute_id: CString, attribute_value: String128) -> TResult"
        }
        ("IUnitInfo", "hasProgramPitchNames") => {
            "unsafe extern \"system\" fn(this: *mut IUnitInfo, list_id: ProgramListID, program_index: int32) -> TResult"
        }
        ("IUnitInfo", "getProgramPitchName") => {
            "unsafe extern \"system\" fn(this: *mut IUnitInfo, list_id: ProgramListID, program_index: int32, midi_pitch: int16, name: String128) -> TResult"
        }
        ("IUnitInfo", "getSelectedUnit") => {
            "unsafe extern \"system\" fn(this: *mut IUnitInfo) -> UnitID"
        }
        ("IUnitInfo", "selectUnit") => {
            "unsafe extern \"system\" fn(this: *mut IUnitInfo, unit_id: UnitID) -> TResult"
        }
        ("IUnitInfo", "getUnitByBus") => {
            "unsafe extern \"system\" fn(this: *mut IUnitInfo, type_: MediaType, dir: BusDirection, bus_index: int32, channel: int32, unit_id: *mut UnitID) -> TResult"
        }
        ("IUnitInfo", "setUnitProgramData") => {
            "unsafe extern \"system\" fn(this: *mut IUnitInfo, list_or_unit_id: int32, program_index: int32, data: *mut IBStream) -> TResult"
        }
        ("IProgramListData", "programDataSupported") => {
            "unsafe extern \"system\" fn(this: *mut IProgramListData, list_id: ProgramListID) -> TResult"
        }
        ("IProgramListData", "getProgramData") => {
            "unsafe extern \"system\" fn(this: *mut IProgramListData, list_id: ProgramListID, program_index: int32, data: *mut IBStream) -> TResult"
        }
        ("IProgramListData", "setProgramData") => {
            "unsafe extern \"system\" fn(this: *mut IProgramListData, list_id: ProgramListID, program_index: int32, data: *mut IBStream) -> TResult"
        }
        _ => {
            return format!(
                "unsafe extern \"system\" fn(this: *mut {}, /* {} parameters: signature-intent pending */) -> TResult",
                method.interface, method.name
            );
        }
    };
    signature.to_string()
}
