use std::path::Path;

use crate::*;

pub fn generated_bindings_scaffold(
    root: impl AsRef<Path>,
    bindings_module: impl AsRef<Path>,
) -> Result<GeneratedBindingsScaffold, GeneratedBindingsScaffoldError> {
    let root = root.as_ref();
    let plan = generated_bindings_plan(root, bindings_module)?;
    let surface = generated_bindings_surface(root)?;
    if !plan.blockers.is_empty() || plan.status != "ready-for-binding-generator" {
        return Err(GeneratedBindingsScaffoldError::Blocked {
            blockers: plan.blockers.clone(),
        });
    }
    if !surface.blockers.is_empty() || surface.status != "ready-for-binding-emitter" {
        return Err(GeneratedBindingsScaffoldError::Blocked {
            blockers: surface.blockers.clone(),
        });
    }
    let module = generated_bindings_scaffold_module(&plan, &surface);
    Ok(GeneratedBindingsScaffold {
        plan,
        surface,
        module,
    })
}

pub fn generated_bindings_abi_seed(
    root: impl AsRef<Path>,
    bindings_module: impl AsRef<Path>,
) -> Result<GeneratedBindingsAbiSeed, GeneratedBindingsScaffoldError> {
    let root = root.as_ref();
    let plan = generated_bindings_plan(root, bindings_module)?;
    let surface = generated_bindings_surface(root)?;
    if !plan.blockers.is_empty() || plan.status != "ready-for-binding-generator" {
        return Err(GeneratedBindingsScaffoldError::Blocked {
            blockers: plan.blockers.clone(),
        });
    }
    if !surface.blockers.is_empty() || surface.status != "ready-for-binding-emitter" {
        return Err(GeneratedBindingsScaffoldError::Blocked {
            blockers: surface.blockers.clone(),
        });
    }
    let module = generated_bindings_abi_seed_module(&plan, &surface);
    Ok(GeneratedBindingsAbiSeed {
        plan,
        surface,
        module,
    })
}

pub fn generated_bindings_abi(
    root: impl AsRef<Path>,
    bindings_module: impl AsRef<Path>,
) -> Result<GeneratedBindingsAbi, GeneratedBindingsScaffoldError> {
    let root = root.as_ref();
    let plan = generated_bindings_plan(root, bindings_module)?;
    let surface = generated_bindings_surface(root)?;
    if !plan.blockers.is_empty() || plan.status != "ready-for-binding-generator" {
        return Err(GeneratedBindingsScaffoldError::Blocked {
            blockers: plan.blockers.clone(),
        });
    }
    if !surface.blockers.is_empty() || surface.status != "ready-for-binding-emitter" {
        return Err(GeneratedBindingsScaffoldError::Blocked {
            blockers: surface.blockers.clone(),
        });
    }
    let module = generated_bindings_abi_module(&plan, &surface);
    Ok(GeneratedBindingsAbi {
        plan,
        surface,
        module,
    })
}

pub fn generated_bindings_interface_skeleton(
    root: impl AsRef<Path>,
    bindings_module: impl AsRef<Path>,
) -> Result<GeneratedBindingsInterfaceSkeleton, GeneratedBindingsScaffoldError> {
    let root = root.as_ref();
    let plan = generated_bindings_plan(root, bindings_module)?;
    let surface = generated_bindings_surface(root)?;
    if !plan.blockers.is_empty() || plan.status != "ready-for-binding-generator" {
        return Err(GeneratedBindingsScaffoldError::Blocked {
            blockers: plan.blockers.clone(),
        });
    }
    if !surface.blockers.is_empty() || surface.status != "ready-for-binding-emitter" {
        return Err(GeneratedBindingsScaffoldError::Blocked {
            blockers: surface.blockers.clone(),
        });
    }
    let module = generated_bindings_interface_skeleton_module(&plan, &surface);
    Ok(GeneratedBindingsInterfaceSkeleton {
        plan,
        surface,
        module,
    })
}

pub fn generated_bindings_scaffold_module(
    plan: &GeneratedBindingsPlan,
    surface: &GeneratedBindingsSurface,
) -> String {
    let mut module = String::new();
    module.push_str("// @generated by ");
    module.push_str(GENERATED_BINDINGS_SCAFFOLD_GENERATOR);
    module.push('\n');
    module.push_str("// This is a metadata-only scaffold for Vesty's reserved VST3 SDK generated-bindings backend.\n");
    module.push_str("// It intentionally does not contain Steinberg VST3 COM/API bindings yet.\n");
    module.push_str("#![allow(dead_code)]\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct HeaderInput {\n");
    module.push_str("    pub path: &'static str,\n");
    module.push_str("    pub size: u64,\n");
    module.push_str("    pub sha256: &'static str,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct BindingSymbol {\n");
    module.push_str("    pub name: &'static str,\n");
    module.push_str("    pub kind: &'static str,\n");
    module.push_str("    pub header: &'static str,\n");
    module.push_str("    pub purpose: &'static str,\n");
    module.push_str("    pub symbol_present: bool,\n");
    module.push_str("}\n\n");
    module.push_str("pub const GENERATOR: &str = ");
    module.push_str(&rust_string_literal(GENERATED_BINDINGS_SCAFFOLD_GENERATOR));
    module.push_str(";\n");
    module.push_str("pub const PLAN_GENERATOR: &str = ");
    module.push_str(&rust_string_literal(&plan.generator));
    module.push_str(";\n");
    module.push_str("pub const SURFACE_GENERATOR: &str = ");
    module.push_str(&rust_string_literal(&surface.generator));
    module.push_str(";\n");
    module.push_str("pub const STATUS: &str = \"metadata-scaffold\";\n");
    module.push_str("pub const PLAN_STATUS: &str = ");
    module.push_str(&rust_string_literal(&plan.status));
    module.push_str(";\n");
    module.push_str("pub const SURFACE_STATUS: &str = ");
    module.push_str(&rust_string_literal(&surface.status));
    module.push_str(";\n");
    module.push_str("pub const BINDINGS_GENERATED: bool = false;\n");
    module.push_str("pub const STEINBERG_VST3_SDK_BASELINE: &str = ");
    module.push_str(&rust_string_literal(&plan.steinberg_sdk_baseline));
    module.push_str(";\n");
    module.push_str("pub const UPSTREAM_VST3_CRATE_BASELINE: &str = ");
    module.push_str(&rust_string_literal(&plan.upstream_vst3_crate_baseline));
    module.push_str(";\n");
    module.push_str("pub const ACTIVE_BACKEND: &str = ");
    module.push_str(&rust_string_literal(&plan.active_backend));
    module.push_str(";\n");
    module.push_str("pub const REQUIRED_HEADER_COUNT: usize = ");
    module.push_str(&plan.header_manifest.headers.len().to_string());
    module.push_str(";\n");
    module.push_str("pub const MISSING_HEADER_COUNT: usize = ");
    module.push_str(&plan.header_manifest.missing_headers.len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub const SURFACE_SYMBOL_COUNT: usize = ");
    module.push_str(&surface.symbols.len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub const HEADER_INPUTS: &[HeaderInput] = &[\n");
    for header in &plan.header_manifest.headers {
        module.push_str("    HeaderInput { path: ");
        module.push_str(&rust_string_literal(&header.path));
        module.push_str(", size: ");
        module.push_str(&header.size.to_string());
        module.push_str(", sha256: ");
        module.push_str(&rust_string_literal(&header.sha256));
        module.push_str(" },\n");
    }
    module.push_str("];\n\n");
    module.push_str("pub const MISSING_HEADERS: &[&str] = &[\n");
    for header in &plan.header_manifest.missing_headers {
        module.push_str("    ");
        module.push_str(&rust_string_literal(header));
        module.push_str(",\n");
    }
    module.push_str("];\n\n");
    module.push_str("pub const BINDING_SURFACE_SYMBOLS: &[BindingSymbol] = &[\n");
    for symbol in &surface.symbols {
        module.push_str("    BindingSymbol { name: ");
        module.push_str(&rust_string_literal(&symbol.name));
        module.push_str(", kind: ");
        module.push_str(&rust_string_literal(&symbol.kind));
        module.push_str(", header: ");
        module.push_str(&rust_string_literal(&symbol.header));
        module.push_str(", purpose: ");
        module.push_str(&rust_string_literal(&symbol.purpose));
        module.push_str(", symbol_present: ");
        module.push_str(if symbol.symbol_present {
            "true"
        } else {
            "false"
        });
        module.push_str(" },\n");
    }
    module.push_str("];\n\n");
    module.push_str("pub const fn bindings_are_generated() -> bool {\n");
    module.push_str("    BINDINGS_GENERATED\n");
    module.push_str("}\n");
    module
}

pub fn generated_bindings_abi_seed_module(
    plan: &GeneratedBindingsPlan,
    surface: &GeneratedBindingsSurface,
) -> String {
    let mut module = String::new();
    module.push_str("// @generated by ");
    module.push_str(GENERATED_BINDINGS_ABI_SEED_GENERATOR);
    module.push('\n');
    module.push_str("// This is a deterministic ABI seed for Vesty's reserved VST3 SDK generated-bindings backend.\n");
    module.push_str("// It contains basic ABI aliases/constants only; full Steinberg VST3 COM/API bindings are not generated yet.\n");
    module.push_str("#![allow(dead_code, non_camel_case_types, non_upper_case_globals)]\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct HeaderInput {\n");
    module.push_str("    pub path: &'static str,\n");
    module.push_str("    pub size: u64,\n");
    module.push_str("    pub sha256: &'static str,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct BindingSymbol {\n");
    module.push_str("    pub name: &'static str,\n");
    module.push_str("    pub kind: &'static str,\n");
    module.push_str("    pub header: &'static str,\n");
    module.push_str("    pub purpose: &'static str,\n");
    module.push_str("    pub symbol_present: bool,\n");
    module.push_str("}\n\n");
    module.push_str("pub const GENERATOR: &str = ");
    module.push_str(&rust_string_literal(GENERATED_BINDINGS_ABI_SEED_GENERATOR));
    module.push_str(";\n");
    module.push_str("pub const PLAN_GENERATOR: &str = ");
    module.push_str(&rust_string_literal(&plan.generator));
    module.push_str(";\n");
    module.push_str("pub const SURFACE_GENERATOR: &str = ");
    module.push_str(&rust_string_literal(&surface.generator));
    module.push_str(";\n");
    module.push_str("pub const STATUS: &str = \"abi-seed\";\n");
    module.push_str("pub const PLAN_STATUS: &str = ");
    module.push_str(&rust_string_literal(&plan.status));
    module.push_str(";\n");
    module.push_str("pub const SURFACE_STATUS: &str = ");
    module.push_str(&rust_string_literal(&surface.status));
    module.push_str(";\n");
    module.push_str("pub const ABI_SEED_GENERATED: bool = true;\n");
    module.push_str("pub const BINDINGS_GENERATED: bool = false;\n");
    module.push_str("pub const FULL_COM_BINDINGS_GENERATED: bool = false;\n");
    module.push_str("pub const STEINBERG_VST3_SDK_BASELINE: &str = ");
    module.push_str(&rust_string_literal(&plan.steinberg_sdk_baseline));
    module.push_str(";\n");
    module.push_str("pub const UPSTREAM_VST3_CRATE_BASELINE: &str = ");
    module.push_str(&rust_string_literal(&plan.upstream_vst3_crate_baseline));
    module.push_str(";\n");
    module.push_str("pub const ACTIVE_BACKEND: &str = ");
    module.push_str(&rust_string_literal(&plan.active_backend));
    module.push_str(";\n");
    module.push_str("pub const REQUIRED_HEADER_COUNT: usize = ");
    module.push_str(&plan.header_manifest.headers.len().to_string());
    module.push_str(";\n");
    module.push_str("pub const MISSING_HEADER_COUNT: usize = ");
    module.push_str(&plan.header_manifest.missing_headers.len().to_string());
    module.push_str(";\n");
    module.push_str("pub const SURFACE_SYMBOL_COUNT: usize = ");
    module.push_str(&surface.symbols.len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub type TResult = i32;\n");
    module.push_str("pub type ParamID = u32;\n");
    module.push_str("pub type ParamValue = f64;\n");
    module.push_str("pub type TChar = u16;\n");
    module.push_str("pub type TUID = [std::os::raw::c_char; 16];\n");
    module.push_str("pub type PlatformType = &'static str;\n\n");
    module.push_str("pub const kResultOk: TResult = 0;\n");
    module.push_str("pub const kInvalidArgument: TResult = 2;\n");
    module.push_str("pub const kNotImplemented: TResult = 3;\n");
    module.push_str("pub const kPlatformTypeHWND: PlatformType = \"HWND\";\n");
    module.push_str("pub const kPlatformTypeNSView: PlatformType = \"NSView\";\n");
    module.push_str(
        "pub const kPlatformTypeX11EmbedWindowID: PlatformType = \"X11EmbedWindowID\";\n\n",
    );
    module.push_str("pub const HEADER_INPUTS: &[HeaderInput] = &[\n");
    for header in &plan.header_manifest.headers {
        module.push_str("    HeaderInput { path: ");
        module.push_str(&rust_string_literal(&header.path));
        module.push_str(", size: ");
        module.push_str(&header.size.to_string());
        module.push_str(", sha256: ");
        module.push_str(&rust_string_literal(&header.sha256));
        module.push_str(" },\n");
    }
    module.push_str("];\n\n");
    module.push_str("pub const MISSING_HEADERS: &[&str] = &[\n");
    for header in &plan.header_manifest.missing_headers {
        module.push_str("    ");
        module.push_str(&rust_string_literal(header));
        module.push_str(",\n");
    }
    module.push_str("];\n\n");
    module.push_str("pub const BINDING_SURFACE_SYMBOLS: &[BindingSymbol] = &[\n");
    for symbol in &surface.symbols {
        module.push_str("    BindingSymbol { name: ");
        module.push_str(&rust_string_literal(&symbol.name));
        module.push_str(", kind: ");
        module.push_str(&rust_string_literal(&symbol.kind));
        module.push_str(", header: ");
        module.push_str(&rust_string_literal(&symbol.header));
        module.push_str(", purpose: ");
        module.push_str(&rust_string_literal(&symbol.purpose));
        module.push_str(", symbol_present: ");
        module.push_str(if symbol.symbol_present {
            "true"
        } else {
            "false"
        });
        module.push_str(" },\n");
    }
    module.push_str("];\n\n");
    module.push_str("pub const fn full_com_bindings_are_generated() -> bool {\n");
    module.push_str("    FULL_COM_BINDINGS_GENERATED\n");
    module.push_str("}\n");
    module
}

pub fn generated_bindings_abi_module(
    plan: &GeneratedBindingsPlan,
    surface: &GeneratedBindingsSurface,
) -> String {
    let mut module = String::new();
    module.push_str("// @generated by ");
    module.push_str(GENERATED_BINDINGS_ABI_GENERATOR);
    module.push('\n');
    module.push_str("// This is a deterministic foundational ABI layout module for Vesty's reserved VST3 SDK generated-bindings backend.\n");
    module.push_str("// It contains repr(C) base layouts and basic aliases/constants only; full Steinberg VST3 COM/API bindings are not generated yet.\n");
    module.push_str(
        "#![allow(dead_code, non_camel_case_types, non_snake_case, non_upper_case_globals)]\n\n",
    );
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct HeaderInput {\n");
    module.push_str("    pub path: &'static str,\n");
    module.push_str("    pub size: u64,\n");
    module.push_str("    pub sha256: &'static str,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct BindingSymbol {\n");
    module.push_str("    pub name: &'static str,\n");
    module.push_str("    pub kind: &'static str,\n");
    module.push_str("    pub header: &'static str,\n");
    module.push_str("    pub purpose: &'static str,\n");
    module.push_str("    pub symbol_present: bool,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct AbiLayoutRecord {\n");
    module.push_str("    pub type_name: &'static str,\n");
    module.push_str("    pub size: usize,\n");
    module.push_str("    pub align: usize,\n");
    module.push_str("}\n\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct AbiFieldOffset {\n");
    module.push_str("    pub owner: &'static str,\n");
    module.push_str("    pub field: &'static str,\n");
    module.push_str("    pub offset: usize,\n");
    module.push_str("}\n\n");
    module.push_str("pub const GENERATOR: &str = ");
    module.push_str(&rust_string_literal(GENERATED_BINDINGS_ABI_GENERATOR));
    module.push_str(";\n");
    module.push_str("pub const PLAN_GENERATOR: &str = ");
    module.push_str(&rust_string_literal(&plan.generator));
    module.push_str(";\n");
    module.push_str("pub const SURFACE_GENERATOR: &str = ");
    module.push_str(&rust_string_literal(&surface.generator));
    module.push_str(";\n");
    module.push_str("pub const STATUS: &str = \"abi-layout\";\n");
    module.push_str("pub const PLAN_STATUS: &str = ");
    module.push_str(&rust_string_literal(&plan.status));
    module.push_str(";\n");
    module.push_str("pub const SURFACE_STATUS: &str = ");
    module.push_str(&rust_string_literal(&surface.status));
    module.push_str(";\n");
    module.push_str("pub const ABI_LAYOUT_GENERATED: bool = true;\n");
    module.push_str("pub const BINDINGS_GENERATED: bool = false;\n");
    module.push_str("pub const FULL_COM_BINDINGS_GENERATED: bool = false;\n");
    module.push_str("pub const STEINBERG_VST3_SDK_BASELINE: &str = ");
    module.push_str(&rust_string_literal(&plan.steinberg_sdk_baseline));
    module.push_str(";\n");
    module.push_str("pub const UPSTREAM_VST3_CRATE_BASELINE: &str = ");
    module.push_str(&rust_string_literal(&plan.upstream_vst3_crate_baseline));
    module.push_str(";\n");
    module.push_str("pub const ACTIVE_BACKEND: &str = ");
    module.push_str(&rust_string_literal(&plan.active_backend));
    module.push_str(";\n");
    module.push_str("pub const REQUIRED_HEADER_COUNT: usize = ");
    module.push_str(&plan.header_manifest.headers.len().to_string());
    module.push_str(";\n");
    module.push_str("pub const MISSING_HEADER_COUNT: usize = ");
    module.push_str(&plan.header_manifest.missing_headers.len().to_string());
    module.push_str(";\n");
    module.push_str("pub const SURFACE_SYMBOL_COUNT: usize = ");
    module.push_str(&surface.symbols.len().to_string());
    module.push_str(";\n\n");
    module.push_str("pub type int32 = i32;\n");
    module.push_str("pub type uint32 = u32;\n");
    module.push_str("pub type int16 = i16;\n");
    module.push_str("pub type uint16 = u16;\n");
    module.push_str("pub type int64 = i64;\n");
    module.push_str("pub type uint64 = u64;\n");
    module.push_str("pub type TBool = u8;\n");
    module.push_str("pub type TResult = i32;\n");
    module.push_str("pub type FIDString = *const std::os::raw::c_char;\n");
    module.push_str("pub type FUnknownPtr = *mut FUnknown;\n");
    module.push_str("pub type ParamID = u32;\n");
    module.push_str("pub type ParamValue = f64;\n");
    module.push_str("pub type TChar = u16;\n");
    module.push_str("pub type String128 = [TChar; STRING128_CODE_UNITS];\n");
    module.push_str("pub type UnitID = int32;\n");
    module.push_str("pub type ProgramListID = int32;\n");
    module.push_str("pub type NoteExpressionTypeID = uint32;\n");
    module.push_str("pub type NoteExpressionValue = f64;\n");
    module.push_str("pub type PhysicalUITypeID = uint32;\n");
    module.push_str("pub type Sample32 = f32;\n");
    module.push_str("pub type Sample64 = f64;\n");
    module.push_str("pub type SampleRate = f64;\n");
    module.push_str("pub type PlatformType = &'static str;\n\n");
    module.push_str("pub const TUID_BYTE_LEN: usize = 16;\n");
    module.push_str("pub const STRING128_CODE_UNITS: usize = 128;\n");
    module.push_str("pub const FUNKNOWN_VTABLE_ENTRIES: usize = 3;\n");
    module.push_str("pub const VIEW_RECT_FIELD_COUNT: usize = 4;\n");
    module.push_str("pub const PROGRAM_LIST_INFO_FIELD_COUNT: usize = 3;\n");
    module.push_str("pub const UNIT_INFO_FIELD_COUNT: usize = 4;\n");
    module.push_str("pub const NOTE_EXPRESSION_TYPE_INFO_FIELD_COUNT: usize = 8;\n");
    module.push_str("pub const PHYSICAL_UI_MAP_FIELD_COUNT: usize = 2;\n");
    module.push_str("pub const kResultOk: TResult = 0;\n");
    module.push_str("pub const kInvalidArgument: TResult = 2;\n");
    module.push_str("pub const kNotImplemented: TResult = 3;\n");
    module.push_str("pub const kRootUnitId: UnitID = 0;\n");
    module.push_str("pub const kNoParentUnitId: UnitID = -1;\n");
    module.push_str("pub const kNoProgramListId: ProgramListID = -1;\n");
    module.push_str("pub const kPlatformTypeHWND: PlatformType = \"HWND\";\n");
    module.push_str("pub const kPlatformTypeNSView: PlatformType = \"NSView\";\n");
    module.push_str(
        "pub const kPlatformTypeX11EmbedWindowID: PlatformType = \"X11EmbedWindowID\";\n\n",
    );
    module.push_str("#[repr(C)]\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct TUID {\n");
    module.push_str("    pub data: [std::os::raw::c_char; TUID_BYTE_LEN],\n");
    module.push_str("}\n\n");
    module.push_str("impl TUID {\n");
    module.push_str("    pub const ZERO: Self = Self { data: [0; TUID_BYTE_LEN] };\n");
    module.push_str("}\n\n");
    module.push_str("pub type FUnknownQueryInterface = unsafe extern \"system\" fn(\n");
    module.push_str("    this: *mut FUnknown,\n");
    module.push_str("    iid: *const TUID,\n");
    module.push_str("    obj: *mut *mut std::ffi::c_void,\n");
    module.push_str(") -> TResult;\n");
    module.push_str(
        "pub type FUnknownAddRef = unsafe extern \"system\" fn(this: *mut FUnknown) -> uint32;\n",
    );
    module.push_str("pub type FUnknownRelease = unsafe extern \"system\" fn(this: *mut FUnknown) -> uint32;\n\n");
    module.push_str("#[repr(C)]\n");
    module.push_str("#[derive(Clone, Copy)]\n");
    module.push_str("pub struct FUnknownVTable {\n");
    module.push_str("    pub queryInterface: FUnknownQueryInterface,\n");
    module.push_str("    pub addRef: FUnknownAddRef,\n");
    module.push_str("    pub release: FUnknownRelease,\n");
    module.push_str("}\n\n");
    module.push_str("#[repr(C)]\n");
    module.push_str("#[derive(Clone, Copy)]\n");
    module.push_str("pub struct FUnknown {\n");
    module.push_str("    pub vtable: *const FUnknownVTable,\n");
    module.push_str("}\n\n");
    module.push_str("#[repr(C)]\n");
    module.push_str("#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]\n");
    module.push_str("pub struct ViewRect {\n");
    module.push_str("    pub left: int32,\n");
    module.push_str("    pub top: int32,\n");
    module.push_str("    pub right: int32,\n");
    module.push_str("    pub bottom: int32,\n");
    module.push_str("}\n\n");
    module.push_str("impl ViewRect {\n");
    module.push_str("    pub const fn width(&self) -> int32 {\n");
    module.push_str("        self.right - self.left\n");
    module.push_str("    }\n\n");
    module.push_str("    pub const fn height(&self) -> int32 {\n");
    module.push_str("        self.bottom - self.top\n");
    module.push_str("    }\n");
    module.push_str("}\n\n");
    module.push_str("#[repr(C)]\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct ProgramListInfo {\n");
    module.push_str("    pub id: ProgramListID,\n");
    module.push_str("    pub name: String128,\n");
    module.push_str("    pub programCount: int32,\n");
    module.push_str("}\n\n");
    module.push_str("#[repr(C)]\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct UnitInfo {\n");
    module.push_str("    pub id: UnitID,\n");
    module.push_str("    pub parentUnitId: UnitID,\n");
    module.push_str("    pub name: String128,\n");
    module.push_str("    pub programListId: ProgramListID,\n");
    module.push_str("}\n\n");
    module.push_str("#[repr(C)]\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq)]\n");
    module.push_str("pub struct NoteExpressionValueDescription {\n");
    module.push_str("    pub defaultValue: NoteExpressionValue,\n");
    module.push_str("    pub minimum: NoteExpressionValue,\n");
    module.push_str("    pub maximum: NoteExpressionValue,\n");
    module.push_str("    pub stepCount: int32,\n");
    module.push_str("}\n\n");
    module.push_str("#[repr(C)]\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq)]\n");
    module.push_str("pub struct NoteExpressionTypeInfo {\n");
    module.push_str("    pub typeId: NoteExpressionTypeID,\n");
    module.push_str("    pub title: String128,\n");
    module.push_str("    pub shortTitle: String128,\n");
    module.push_str("    pub units: String128,\n");
    module.push_str("    pub unitId: int32,\n");
    module.push_str("    pub valueDesc: NoteExpressionValueDescription,\n");
    module.push_str("    pub associatedParameterId: ParamID,\n");
    module.push_str("    pub flags: int32,\n");
    module.push_str("}\n\n");
    module.push_str("#[repr(C)]\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct PhysicalUIMap {\n");
    module.push_str("    pub physicalUITypeID: PhysicalUITypeID,\n");
    module.push_str("    pub noteExpressionTypeID: NoteExpressionTypeID,\n");
    module.push_str("}\n\n");
    module.push_str("#[repr(C)]\n");
    module.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    module.push_str("pub struct PhysicalUIMapList {\n");
    module.push_str("    pub count: uint32,\n");
    module.push_str("    pub map: *mut PhysicalUIMap,\n");
    module.push_str("}\n\n");
    module.push_str("pub const ABI_LAYOUT_TYPES: &[&str] = &[\n");
    for ty in [
        "TUID",
        "FUnknownVTable",
        "FUnknown",
        "ViewRect",
        "ProgramListInfo",
        "UnitInfo",
        "NoteExpressionValueDescription",
        "NoteExpressionTypeInfo",
        "PhysicalUIMap",
        "PhysicalUIMapList",
        "TResult",
        "ParamID",
        "ParamValue",
        "TChar",
        "String128",
        "UnitID",
        "ProgramListID",
        "NoteExpressionTypeID",
        "NoteExpressionValue",
        "PhysicalUITypeID",
        "Sample32",
        "Sample64",
    ] {
        module.push_str("    ");
        module.push_str(&rust_string_literal(ty));
        module.push_str(",\n");
    }
    module.push_str("];\n\n");
    module.push_str("pub const ABI_LAYOUT_RECORDS: &[AbiLayoutRecord] = &[\n");
    for ty in [
        "TUID",
        "FUnknownVTable",
        "FUnknown",
        "ViewRect",
        "ProgramListInfo",
        "UnitInfo",
        "NoteExpressionValueDescription",
        "NoteExpressionTypeInfo",
        "PhysicalUIMap",
        "PhysicalUIMapList",
        "TResult",
        "ParamID",
        "ParamValue",
        "TChar",
        "String128",
        "UnitID",
        "ProgramListID",
        "NoteExpressionTypeID",
        "NoteExpressionValue",
        "PhysicalUITypeID",
        "Sample32",
        "Sample64",
    ] {
        module.push_str("    AbiLayoutRecord { type_name: ");
        module.push_str(&rust_string_literal(ty));
        module.push_str(", size: std::mem::size_of::<");
        module.push_str(ty);
        module.push_str(">(), align: std::mem::align_of::<");
        module.push_str(ty);
        module.push_str(">() },\n");
    }
    module.push_str("];\n\n");
    module.push_str("pub const ABI_FIELD_OFFSETS: &[AbiFieldOffset] = &[\n");
    for (owner, field) in [
        ("TUID", "data"),
        ("FUnknownVTable", "queryInterface"),
        ("FUnknownVTable", "addRef"),
        ("FUnknownVTable", "release"),
        ("FUnknown", "vtable"),
        ("ViewRect", "left"),
        ("ViewRect", "top"),
        ("ViewRect", "right"),
        ("ViewRect", "bottom"),
        ("ProgramListInfo", "id"),
        ("ProgramListInfo", "name"),
        ("ProgramListInfo", "programCount"),
        ("UnitInfo", "id"),
        ("UnitInfo", "parentUnitId"),
        ("UnitInfo", "name"),
        ("UnitInfo", "programListId"),
        ("NoteExpressionValueDescription", "defaultValue"),
        ("NoteExpressionValueDescription", "minimum"),
        ("NoteExpressionValueDescription", "maximum"),
        ("NoteExpressionValueDescription", "stepCount"),
        ("NoteExpressionTypeInfo", "typeId"),
        ("NoteExpressionTypeInfo", "title"),
        ("NoteExpressionTypeInfo", "shortTitle"),
        ("NoteExpressionTypeInfo", "units"),
        ("NoteExpressionTypeInfo", "unitId"),
        ("NoteExpressionTypeInfo", "valueDesc"),
        ("NoteExpressionTypeInfo", "associatedParameterId"),
        ("NoteExpressionTypeInfo", "flags"),
        ("PhysicalUIMap", "physicalUITypeID"),
        ("PhysicalUIMap", "noteExpressionTypeID"),
        ("PhysicalUIMapList", "count"),
        ("PhysicalUIMapList", "map"),
    ] {
        module.push_str("    AbiFieldOffset { owner: ");
        module.push_str(&rust_string_literal(owner));
        module.push_str(", field: ");
        module.push_str(&rust_string_literal(field));
        module.push_str(", offset: std::mem::offset_of!(");
        module.push_str(owner);
        module.push_str(", ");
        module.push_str(field);
        module.push_str(") },\n");
    }
    module.push_str("];\n\n");
    module.push_str("pub const HEADER_INPUTS: &[HeaderInput] = &[\n");
    for header in &plan.header_manifest.headers {
        module.push_str("    HeaderInput { path: ");
        module.push_str(&rust_string_literal(&header.path));
        module.push_str(", size: ");
        module.push_str(&header.size.to_string());
        module.push_str(", sha256: ");
        module.push_str(&rust_string_literal(&header.sha256));
        module.push_str(" },\n");
    }
    module.push_str("];\n\n");
    module.push_str("pub const MISSING_HEADERS: &[&str] = &[\n");
    for header in &plan.header_manifest.missing_headers {
        module.push_str("    ");
        module.push_str(&rust_string_literal(header));
        module.push_str(",\n");
    }
    module.push_str("];\n\n");
    module.push_str("pub const BINDING_SURFACE_SYMBOLS: &[BindingSymbol] = &[\n");
    for symbol in &surface.symbols {
        module.push_str("    BindingSymbol { name: ");
        module.push_str(&rust_string_literal(&symbol.name));
        module.push_str(", kind: ");
        module.push_str(&rust_string_literal(&symbol.kind));
        module.push_str(", header: ");
        module.push_str(&rust_string_literal(&symbol.header));
        module.push_str(", purpose: ");
        module.push_str(&rust_string_literal(&symbol.purpose));
        module.push_str(", symbol_present: ");
        module.push_str(if symbol.symbol_present {
            "true"
        } else {
            "false"
        });
        module.push_str(" },\n");
    }
    module.push_str("];\n\n");
    module.push_str("pub const fn abi_layout_is_generated() -> bool {\n");
    module.push_str("    ABI_LAYOUT_GENERATED\n");
    module.push_str("}\n\n");
    module.push_str("pub const fn full_com_bindings_are_generated() -> bool {\n");
    module.push_str("    FULL_COM_BINDINGS_GENERATED\n");
    module.push_str("}\n");
    module
}
